// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: cstrike15_usermessages_public.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_VGUIMenu")]
public partial class CCSUsrMsgVGUIMenu : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"name")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Name
    {
        get { return __pbn__Name ?? ""; }
        set { __pbn__Name = value; }
    }
    public bool ShouldSerializeName() => __pbn__Name != null;
    public void ResetName() => __pbn__Name = null;
    private string __pbn__Name;

    [global::ProtoBuf.ProtoMember(2, Name = @"show")]
    public bool Show
    {
        get { return __pbn__Show.GetValueOrDefault(); }
        set { __pbn__Show = value; }
    }
    public bool ShouldSerializeShow() => __pbn__Show != null;
    public void ResetShow() => __pbn__Show = null;
    private bool? __pbn__Show;

    [global::ProtoBuf.ProtoMember(3, Name = @"subkeys")]
    public global::System.Collections.Generic.List<Subkey> Subkeys { get; } = new global::System.Collections.Generic.List<Subkey>();

    [global::ProtoBuf.ProtoContract()]
    public partial class Subkey : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get { return __pbn__Name ?? ""; }
            set { __pbn__Name = value; }
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(2, Name = @"str")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Str
        {
            get { return __pbn__Str ?? ""; }
            set { __pbn__Str = value; }
        }
        public bool ShouldSerializeStr() => __pbn__Str != null;
        public void ResetStr() => __pbn__Str = null;
        private string __pbn__Str;

    }

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_Geiger")]
public partial class CCSUsrMsgGeiger : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"range")]
    public int Range
    {
        get { return __pbn__Range.GetValueOrDefault(); }
        set { __pbn__Range = value; }
    }
    public bool ShouldSerializeRange() => __pbn__Range != null;
    public void ResetRange() => __pbn__Range = null;
    private int? __pbn__Range;

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_Train")]
public partial class CCSUsrMsgTrain : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"train")]
    public int Train
    {
        get { return __pbn__Train.GetValueOrDefault(); }
        set { __pbn__Train = value; }
    }
    public bool ShouldSerializeTrain() => __pbn__Train != null;
    public void ResetTrain() => __pbn__Train = null;
    private int? __pbn__Train;

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_HudText")]
public partial class CCSUsrMsgHudText : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"text")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Text
    {
        get { return __pbn__Text ?? ""; }
        set { __pbn__Text = value; }
    }
    public bool ShouldSerializeText() => __pbn__Text != null;
    public void ResetText() => __pbn__Text = null;
    private string __pbn__Text;

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_SayText")]
public partial class CCSUsrMsgSayText : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"ent_idx")]
    public int EntIdx
    {
        get { return __pbn__EntIdx.GetValueOrDefault(); }
        set { __pbn__EntIdx = value; }
    }
    public bool ShouldSerializeEntIdx() => __pbn__EntIdx != null;
    public void ResetEntIdx() => __pbn__EntIdx = null;
    private int? __pbn__EntIdx;

    [global::ProtoBuf.ProtoMember(2, Name = @"text")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Text
    {
        get { return __pbn__Text ?? ""; }
        set { __pbn__Text = value; }
    }
    public bool ShouldSerializeText() => __pbn__Text != null;
    public void ResetText() => __pbn__Text = null;
    private string __pbn__Text;

    [global::ProtoBuf.ProtoMember(3, Name = @"chat")]
    public bool Chat
    {
        get { return __pbn__Chat.GetValueOrDefault(); }
        set { __pbn__Chat = value; }
    }
    public bool ShouldSerializeChat() => __pbn__Chat != null;
    public void ResetChat() => __pbn__Chat = null;
    private bool? __pbn__Chat;

    [global::ProtoBuf.ProtoMember(4, Name = @"textallchat")]
    public bool Textallchat
    {
        get { return __pbn__Textallchat.GetValueOrDefault(); }
        set { __pbn__Textallchat = value; }
    }
    public bool ShouldSerializeTextallchat() => __pbn__Textallchat != null;
    public void ResetTextallchat() => __pbn__Textallchat = null;
    private bool? __pbn__Textallchat;

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_SayText2")]
public partial class CCSUsrMsgSayText2 : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"ent_idx")]
    public int EntIdx
    {
        get { return __pbn__EntIdx.GetValueOrDefault(); }
        set { __pbn__EntIdx = value; }
    }
    public bool ShouldSerializeEntIdx() => __pbn__EntIdx != null;
    public void ResetEntIdx() => __pbn__EntIdx = null;
    private int? __pbn__EntIdx;

    [global::ProtoBuf.ProtoMember(2, Name = @"chat")]
    public bool Chat
    {
        get { return __pbn__Chat.GetValueOrDefault(); }
        set { __pbn__Chat = value; }
    }
    public bool ShouldSerializeChat() => __pbn__Chat != null;
    public void ResetChat() => __pbn__Chat = null;
    private bool? __pbn__Chat;

    [global::ProtoBuf.ProtoMember(3, Name = @"msg_name")]
    [global::System.ComponentModel.DefaultValue("")]
    public string MsgName
    {
        get { return __pbn__MsgName ?? ""; }
        set { __pbn__MsgName = value; }
    }
    public bool ShouldSerializeMsgName() => __pbn__MsgName != null;
    public void ResetMsgName() => __pbn__MsgName = null;
    private string __pbn__MsgName;

    [global::ProtoBuf.ProtoMember(4, Name = @"params")]
    public global::System.Collections.Generic.List<string> Params { get; } = new global::System.Collections.Generic.List<string>();

    [global::ProtoBuf.ProtoMember(5, Name = @"textallchat")]
    public bool Textallchat
    {
        get { return __pbn__Textallchat.GetValueOrDefault(); }
        set { __pbn__Textallchat = value; }
    }
    public bool ShouldSerializeTextallchat() => __pbn__Textallchat != null;
    public void ResetTextallchat() => __pbn__Textallchat = null;
    private bool? __pbn__Textallchat;

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_TextMsg")]
public partial class CCSUsrMsgTextMsg : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"msg_dst")]
    public int MsgDst
    {
        get { return __pbn__MsgDst.GetValueOrDefault(); }
        set { __pbn__MsgDst = value; }
    }
    public bool ShouldSerializeMsgDst() => __pbn__MsgDst != null;
    public void ResetMsgDst() => __pbn__MsgDst = null;
    private int? __pbn__MsgDst;

    [global::ProtoBuf.ProtoMember(3, Name = @"params")]
    public global::System.Collections.Generic.List<string> Params { get; } = new global::System.Collections.Generic.List<string>();

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_HudMsg")]
public partial class CCSUsrMsgHudMsg : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"channel")]
    public int Channel
    {
        get { return __pbn__Channel.GetValueOrDefault(); }
        set { __pbn__Channel = value; }
    }
    public bool ShouldSerializeChannel() => __pbn__Channel != null;
    public void ResetChannel() => __pbn__Channel = null;
    private int? __pbn__Channel;

    [global::ProtoBuf.ProtoMember(2, Name = @"pos")]
    public CMsgVector2D Pos { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"clr1")]
    public CMsgRGBA Clr1 { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"clr2")]
    public CMsgRGBA Clr2 { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"effect")]
    public int Effect
    {
        get { return __pbn__Effect.GetValueOrDefault(); }
        set { __pbn__Effect = value; }
    }
    public bool ShouldSerializeEffect() => __pbn__Effect != null;
    public void ResetEffect() => __pbn__Effect = null;
    private int? __pbn__Effect;

    [global::ProtoBuf.ProtoMember(6, Name = @"fade_in_time")]
    public float FadeInTime
    {
        get { return __pbn__FadeInTime.GetValueOrDefault(); }
        set { __pbn__FadeInTime = value; }
    }
    public bool ShouldSerializeFadeInTime() => __pbn__FadeInTime != null;
    public void ResetFadeInTime() => __pbn__FadeInTime = null;
    private float? __pbn__FadeInTime;

    [global::ProtoBuf.ProtoMember(7, Name = @"fade_out_time")]
    public float FadeOutTime
    {
        get { return __pbn__FadeOutTime.GetValueOrDefault(); }
        set { __pbn__FadeOutTime = value; }
    }
    public bool ShouldSerializeFadeOutTime() => __pbn__FadeOutTime != null;
    public void ResetFadeOutTime() => __pbn__FadeOutTime = null;
    private float? __pbn__FadeOutTime;

    [global::ProtoBuf.ProtoMember(9, Name = @"hold_time")]
    public float HoldTime
    {
        get { return __pbn__HoldTime.GetValueOrDefault(); }
        set { __pbn__HoldTime = value; }
    }
    public bool ShouldSerializeHoldTime() => __pbn__HoldTime != null;
    public void ResetHoldTime() => __pbn__HoldTime = null;
    private float? __pbn__HoldTime;

    [global::ProtoBuf.ProtoMember(10, Name = @"fx_time")]
    public float FxTime
    {
        get { return __pbn__FxTime.GetValueOrDefault(); }
        set { __pbn__FxTime = value; }
    }
    public bool ShouldSerializeFxTime() => __pbn__FxTime != null;
    public void ResetFxTime() => __pbn__FxTime = null;
    private float? __pbn__FxTime;

    [global::ProtoBuf.ProtoMember(11, Name = @"text")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Text
    {
        get { return __pbn__Text ?? ""; }
        set { __pbn__Text = value; }
    }
    public bool ShouldSerializeText() => __pbn__Text != null;
    public void ResetText() => __pbn__Text = null;
    private string __pbn__Text;

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_Shake")]
public partial class CCSUsrMsgShake : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"command")]
    public int Command
    {
        get { return __pbn__Command.GetValueOrDefault(); }
        set { __pbn__Command = value; }
    }
    public bool ShouldSerializeCommand() => __pbn__Command != null;
    public void ResetCommand() => __pbn__Command = null;
    private int? __pbn__Command;

    [global::ProtoBuf.ProtoMember(2, Name = @"local_amplitude")]
    public float LocalAmplitude
    {
        get { return __pbn__LocalAmplitude.GetValueOrDefault(); }
        set { __pbn__LocalAmplitude = value; }
    }
    public bool ShouldSerializeLocalAmplitude() => __pbn__LocalAmplitude != null;
    public void ResetLocalAmplitude() => __pbn__LocalAmplitude = null;
    private float? __pbn__LocalAmplitude;

    [global::ProtoBuf.ProtoMember(3, Name = @"frequency")]
    public float Frequency
    {
        get { return __pbn__Frequency.GetValueOrDefault(); }
        set { __pbn__Frequency = value; }
    }
    public bool ShouldSerializeFrequency() => __pbn__Frequency != null;
    public void ResetFrequency() => __pbn__Frequency = null;
    private float? __pbn__Frequency;

    [global::ProtoBuf.ProtoMember(4, Name = @"duration")]
    public float Duration
    {
        get { return __pbn__Duration.GetValueOrDefault(); }
        set { __pbn__Duration = value; }
    }
    public bool ShouldSerializeDuration() => __pbn__Duration != null;
    public void ResetDuration() => __pbn__Duration = null;
    private float? __pbn__Duration;

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_Fade")]
public partial class CCSUsrMsgFade : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"duration")]
    public int Duration
    {
        get { return __pbn__Duration.GetValueOrDefault(); }
        set { __pbn__Duration = value; }
    }
    public bool ShouldSerializeDuration() => __pbn__Duration != null;
    public void ResetDuration() => __pbn__Duration = null;
    private int? __pbn__Duration;

    [global::ProtoBuf.ProtoMember(2, Name = @"hold_time")]
    public int HoldTime
    {
        get { return __pbn__HoldTime.GetValueOrDefault(); }
        set { __pbn__HoldTime = value; }
    }
    public bool ShouldSerializeHoldTime() => __pbn__HoldTime != null;
    public void ResetHoldTime() => __pbn__HoldTime = null;
    private int? __pbn__HoldTime;

    [global::ProtoBuf.ProtoMember(3, Name = @"flags")]
    public int Flags
    {
        get { return __pbn__Flags.GetValueOrDefault(); }
        set { __pbn__Flags = value; }
    }
    public bool ShouldSerializeFlags() => __pbn__Flags != null;
    public void ResetFlags() => __pbn__Flags = null;
    private int? __pbn__Flags;

    [global::ProtoBuf.ProtoMember(4, Name = @"clr")]
    public CMsgRGBA Clr { get; set; }

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_Rumble")]
public partial class CCSUsrMsgRumble : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"index")]
    public int Index
    {
        get { return __pbn__Index.GetValueOrDefault(); }
        set { __pbn__Index = value; }
    }
    public bool ShouldSerializeIndex() => __pbn__Index != null;
    public void ResetIndex() => __pbn__Index = null;
    private int? __pbn__Index;

    [global::ProtoBuf.ProtoMember(2, Name = @"data")]
    public int Data
    {
        get { return __pbn__Data.GetValueOrDefault(); }
        set { __pbn__Data = value; }
    }
    public bool ShouldSerializeData() => __pbn__Data != null;
    public void ResetData() => __pbn__Data = null;
    private int? __pbn__Data;

    [global::ProtoBuf.ProtoMember(3, Name = @"flags")]
    public int Flags
    {
        get { return __pbn__Flags.GetValueOrDefault(); }
        set { __pbn__Flags = value; }
    }
    public bool ShouldSerializeFlags() => __pbn__Flags != null;
    public void ResetFlags() => __pbn__Flags = null;
    private int? __pbn__Flags;

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_CloseCaption")]
public partial class CCSUsrMsgCloseCaption : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"hash")]
    public uint Hash
    {
        get { return __pbn__Hash.GetValueOrDefault(); }
        set { __pbn__Hash = value; }
    }
    public bool ShouldSerializeHash() => __pbn__Hash != null;
    public void ResetHash() => __pbn__Hash = null;
    private uint? __pbn__Hash;

    [global::ProtoBuf.ProtoMember(2, Name = @"duration")]
    public int Duration
    {
        get { return __pbn__Duration.GetValueOrDefault(); }
        set { __pbn__Duration = value; }
    }
    public bool ShouldSerializeDuration() => __pbn__Duration != null;
    public void ResetDuration() => __pbn__Duration = null;
    private int? __pbn__Duration;

    [global::ProtoBuf.ProtoMember(3, Name = @"from_player")]
    public bool FromPlayer
    {
        get { return __pbn__FromPlayer.GetValueOrDefault(); }
        set { __pbn__FromPlayer = value; }
    }
    public bool ShouldSerializeFromPlayer() => __pbn__FromPlayer != null;
    public void ResetFromPlayer() => __pbn__FromPlayer = null;
    private bool? __pbn__FromPlayer;

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_CloseCaptionDirect")]
public partial class CCSUsrMsgCloseCaptionDirect : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"hash")]
    public uint Hash
    {
        get { return __pbn__Hash.GetValueOrDefault(); }
        set { __pbn__Hash = value; }
    }
    public bool ShouldSerializeHash() => __pbn__Hash != null;
    public void ResetHash() => __pbn__Hash = null;
    private uint? __pbn__Hash;

    [global::ProtoBuf.ProtoMember(2, Name = @"duration")]
    public int Duration
    {
        get { return __pbn__Duration.GetValueOrDefault(); }
        set { __pbn__Duration = value; }
    }
    public bool ShouldSerializeDuration() => __pbn__Duration != null;
    public void ResetDuration() => __pbn__Duration = null;
    private int? __pbn__Duration;

    [global::ProtoBuf.ProtoMember(3, Name = @"from_player")]
    public bool FromPlayer
    {
        get { return __pbn__FromPlayer.GetValueOrDefault(); }
        set { __pbn__FromPlayer = value; }
    }
    public bool ShouldSerializeFromPlayer() => __pbn__FromPlayer != null;
    public void ResetFromPlayer() => __pbn__FromPlayer = null;
    private bool? __pbn__FromPlayer;

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_SendAudio")]
public partial class CCSUsrMsgSendAudio : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"radio_sound")]
    [global::System.ComponentModel.DefaultValue("")]
    public string RadioSound
    {
        get { return __pbn__RadioSound ?? ""; }
        set { __pbn__RadioSound = value; }
    }
    public bool ShouldSerializeRadioSound() => __pbn__RadioSound != null;
    public void ResetRadioSound() => __pbn__RadioSound = null;
    private string __pbn__RadioSound;

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_RawAudio")]
public partial class CCSUsrMsgRawAudio : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"pitch")]
    public int Pitch
    {
        get { return __pbn__Pitch.GetValueOrDefault(); }
        set { __pbn__Pitch = value; }
    }
    public bool ShouldSerializePitch() => __pbn__Pitch != null;
    public void ResetPitch() => __pbn__Pitch = null;
    private int? __pbn__Pitch;

    [global::ProtoBuf.ProtoMember(2, Name = @"entidx")]
    public int Entidx
    {
        get { return __pbn__Entidx.GetValueOrDefault(); }
        set { __pbn__Entidx = value; }
    }
    public bool ShouldSerializeEntidx() => __pbn__Entidx != null;
    public void ResetEntidx() => __pbn__Entidx = null;
    private int? __pbn__Entidx;

    [global::ProtoBuf.ProtoMember(3, Name = @"duration")]
    public float Duration
    {
        get { return __pbn__Duration.GetValueOrDefault(); }
        set { __pbn__Duration = value; }
    }
    public bool ShouldSerializeDuration() => __pbn__Duration != null;
    public void ResetDuration() => __pbn__Duration = null;
    private float? __pbn__Duration;

    [global::ProtoBuf.ProtoMember(4, Name = @"voice_filename")]
    [global::System.ComponentModel.DefaultValue("")]
    public string VoiceFilename
    {
        get { return __pbn__VoiceFilename ?? ""; }
        set { __pbn__VoiceFilename = value; }
    }
    public bool ShouldSerializeVoiceFilename() => __pbn__VoiceFilename != null;
    public void ResetVoiceFilename() => __pbn__VoiceFilename = null;
    private string __pbn__VoiceFilename;

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_VoiceMask")]
public partial class CCSUsrMsgVoiceMask : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"player_masks")]
    public global::System.Collections.Generic.List<PlayerMask> PlayerMasks { get; } = new global::System.Collections.Generic.List<PlayerMask>();

    [global::ProtoBuf.ProtoMember(2, Name = @"player_mod_enable")]
    public bool PlayerModEnable
    {
        get { return __pbn__PlayerModEnable.GetValueOrDefault(); }
        set { __pbn__PlayerModEnable = value; }
    }
    public bool ShouldSerializePlayerModEnable() => __pbn__PlayerModEnable != null;
    public void ResetPlayerModEnable() => __pbn__PlayerModEnable = null;
    private bool? __pbn__PlayerModEnable;

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerMask : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"game_rules_mask")]
        public int GameRulesMask
        {
            get { return __pbn__GameRulesMask.GetValueOrDefault(); }
            set { __pbn__GameRulesMask = value; }
        }
        public bool ShouldSerializeGameRulesMask() => __pbn__GameRulesMask != null;
        public void ResetGameRulesMask() => __pbn__GameRulesMask = null;
        private int? __pbn__GameRulesMask;

        [global::ProtoBuf.ProtoMember(2, Name = @"ban_masks")]
        public int BanMasks
        {
            get { return __pbn__BanMasks.GetValueOrDefault(); }
            set { __pbn__BanMasks = value; }
        }
        public bool ShouldSerializeBanMasks() => __pbn__BanMasks != null;
        public void ResetBanMasks() => __pbn__BanMasks = null;
        private int? __pbn__BanMasks;

    }

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_Damage")]
public partial class CCSUsrMsgDamage : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"amount")]
    public int Amount
    {
        get { return __pbn__Amount.GetValueOrDefault(); }
        set { __pbn__Amount = value; }
    }
    public bool ShouldSerializeAmount() => __pbn__Amount != null;
    public void ResetAmount() => __pbn__Amount = null;
    private int? __pbn__Amount;

    [global::ProtoBuf.ProtoMember(2, Name = @"inflictor_world_pos")]
    public CMsgVector InflictorWorldPos { get; set; }

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_RadioText")]
public partial class CCSUsrMsgRadioText : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"msg_dst")]
    public int MsgDst
    {
        get { return __pbn__MsgDst.GetValueOrDefault(); }
        set { __pbn__MsgDst = value; }
    }
    public bool ShouldSerializeMsgDst() => __pbn__MsgDst != null;
    public void ResetMsgDst() => __pbn__MsgDst = null;
    private int? __pbn__MsgDst;

    [global::ProtoBuf.ProtoMember(2, Name = @"client")]
    public int Client
    {
        get { return __pbn__Client.GetValueOrDefault(); }
        set { __pbn__Client = value; }
    }
    public bool ShouldSerializeClient() => __pbn__Client != null;
    public void ResetClient() => __pbn__Client = null;
    private int? __pbn__Client;

    [global::ProtoBuf.ProtoMember(3, Name = @"msg_name")]
    [global::System.ComponentModel.DefaultValue("")]
    public string MsgName
    {
        get { return __pbn__MsgName ?? ""; }
        set { __pbn__MsgName = value; }
    }
    public bool ShouldSerializeMsgName() => __pbn__MsgName != null;
    public void ResetMsgName() => __pbn__MsgName = null;
    private string __pbn__MsgName;

    [global::ProtoBuf.ProtoMember(4, Name = @"params")]
    public global::System.Collections.Generic.List<string> Params { get; } = new global::System.Collections.Generic.List<string>();

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_HintText")]
public partial class CCSUsrMsgHintText : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"text")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Text
    {
        get { return __pbn__Text ?? ""; }
        set { __pbn__Text = value; }
    }
    public bool ShouldSerializeText() => __pbn__Text != null;
    public void ResetText() => __pbn__Text = null;
    private string __pbn__Text;

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_KeyHintText")]
public partial class CCSUsrMsgKeyHintText : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"hints")]
    public global::System.Collections.Generic.List<string> Hints { get; } = new global::System.Collections.Generic.List<string>();

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_ProcessSpottedEntityUpdate")]
public partial class CCSUsrMsgProcessSpottedEntityUpdate : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"new_update")]
    public bool NewUpdate
    {
        get { return __pbn__NewUpdate.GetValueOrDefault(); }
        set { __pbn__NewUpdate = value; }
    }
    public bool ShouldSerializeNewUpdate() => __pbn__NewUpdate != null;
    public void ResetNewUpdate() => __pbn__NewUpdate = null;
    private bool? __pbn__NewUpdate;

    [global::ProtoBuf.ProtoMember(2, Name = @"entity_updates")]
    public global::System.Collections.Generic.List<SpottedEntityUpdate> EntityUpdates { get; } = new global::System.Collections.Generic.List<SpottedEntityUpdate>();

    [global::ProtoBuf.ProtoContract()]
    public partial class SpottedEntityUpdate : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"entity_idx")]
        public int EntityIdx
        {
            get { return __pbn__EntityIdx.GetValueOrDefault(); }
            set { __pbn__EntityIdx = value; }
        }
        public bool ShouldSerializeEntityIdx() => __pbn__EntityIdx != null;
        public void ResetEntityIdx() => __pbn__EntityIdx = null;
        private int? __pbn__EntityIdx;

        [global::ProtoBuf.ProtoMember(2, Name = @"class_id")]
        public int ClassId
        {
            get { return __pbn__ClassId.GetValueOrDefault(); }
            set { __pbn__ClassId = value; }
        }
        public bool ShouldSerializeClassId() => __pbn__ClassId != null;
        public void ResetClassId() => __pbn__ClassId = null;
        private int? __pbn__ClassId;

        [global::ProtoBuf.ProtoMember(3, Name = @"origin_x")]
        public int OriginX
        {
            get { return __pbn__OriginX.GetValueOrDefault(); }
            set { __pbn__OriginX = value; }
        }
        public bool ShouldSerializeOriginX() => __pbn__OriginX != null;
        public void ResetOriginX() => __pbn__OriginX = null;
        private int? __pbn__OriginX;

        [global::ProtoBuf.ProtoMember(4, Name = @"origin_y")]
        public int OriginY
        {
            get { return __pbn__OriginY.GetValueOrDefault(); }
            set { __pbn__OriginY = value; }
        }
        public bool ShouldSerializeOriginY() => __pbn__OriginY != null;
        public void ResetOriginY() => __pbn__OriginY = null;
        private int? __pbn__OriginY;

        [global::ProtoBuf.ProtoMember(5, Name = @"origin_z")]
        public int OriginZ
        {
            get { return __pbn__OriginZ.GetValueOrDefault(); }
            set { __pbn__OriginZ = value; }
        }
        public bool ShouldSerializeOriginZ() => __pbn__OriginZ != null;
        public void ResetOriginZ() => __pbn__OriginZ = null;
        private int? __pbn__OriginZ;

        [global::ProtoBuf.ProtoMember(6, Name = @"angle_y")]
        public int AngleY
        {
            get { return __pbn__AngleY.GetValueOrDefault(); }
            set { __pbn__AngleY = value; }
        }
        public bool ShouldSerializeAngleY() => __pbn__AngleY != null;
        public void ResetAngleY() => __pbn__AngleY = null;
        private int? __pbn__AngleY;

        [global::ProtoBuf.ProtoMember(7, Name = @"defuser")]
        public bool Defuser
        {
            get { return __pbn__Defuser.GetValueOrDefault(); }
            set { __pbn__Defuser = value; }
        }
        public bool ShouldSerializeDefuser() => __pbn__Defuser != null;
        public void ResetDefuser() => __pbn__Defuser = null;
        private bool? __pbn__Defuser;

        [global::ProtoBuf.ProtoMember(8, Name = @"player_has_defuser")]
        public bool PlayerHasDefuser
        {
            get { return __pbn__PlayerHasDefuser.GetValueOrDefault(); }
            set { __pbn__PlayerHasDefuser = value; }
        }
        public bool ShouldSerializePlayerHasDefuser() => __pbn__PlayerHasDefuser != null;
        public void ResetPlayerHasDefuser() => __pbn__PlayerHasDefuser = null;
        private bool? __pbn__PlayerHasDefuser;

        [global::ProtoBuf.ProtoMember(9, Name = @"player_has_c4")]
        public bool PlayerHasC4
        {
            get { return __pbn__PlayerHasC4.GetValueOrDefault(); }
            set { __pbn__PlayerHasC4 = value; }
        }
        public bool ShouldSerializePlayerHasC4() => __pbn__PlayerHasC4 != null;
        public void ResetPlayerHasC4() => __pbn__PlayerHasC4 = null;
        private bool? __pbn__PlayerHasC4;

    }

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_ReloadEffect")]
public partial class CCSUsrMsgReloadEffect : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"entidx")]
    public int Entidx
    {
        get { return __pbn__Entidx.GetValueOrDefault(); }
        set { __pbn__Entidx = value; }
    }
    public bool ShouldSerializeEntidx() => __pbn__Entidx != null;
    public void ResetEntidx() => __pbn__Entidx = null;
    private int? __pbn__Entidx;

    [global::ProtoBuf.ProtoMember(2, Name = @"actanim")]
    public int Actanim
    {
        get { return __pbn__Actanim.GetValueOrDefault(); }
        set { __pbn__Actanim = value; }
    }
    public bool ShouldSerializeActanim() => __pbn__Actanim != null;
    public void ResetActanim() => __pbn__Actanim = null;
    private int? __pbn__Actanim;

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_AdjustMoney")]
public partial class CCSUsrMsgAdjustMoney : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"amount")]
    public int Amount
    {
        get { return __pbn__Amount.GetValueOrDefault(); }
        set { __pbn__Amount = value; }
    }
    public bool ShouldSerializeAmount() => __pbn__Amount != null;
    public void ResetAmount() => __pbn__Amount = null;
    private int? __pbn__Amount;

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_KillCam")]
public partial class CCSUsrMsgKillCam : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"obs_mode")]
    public int ObsMode
    {
        get { return __pbn__ObsMode.GetValueOrDefault(); }
        set { __pbn__ObsMode = value; }
    }
    public bool ShouldSerializeObsMode() => __pbn__ObsMode != null;
    public void ResetObsMode() => __pbn__ObsMode = null;
    private int? __pbn__ObsMode;

    [global::ProtoBuf.ProtoMember(2, Name = @"first_target")]
    public int FirstTarget
    {
        get { return __pbn__FirstTarget.GetValueOrDefault(); }
        set { __pbn__FirstTarget = value; }
    }
    public bool ShouldSerializeFirstTarget() => __pbn__FirstTarget != null;
    public void ResetFirstTarget() => __pbn__FirstTarget = null;
    private int? __pbn__FirstTarget;

    [global::ProtoBuf.ProtoMember(3, Name = @"second_target")]
    public int SecondTarget
    {
        get { return __pbn__SecondTarget.GetValueOrDefault(); }
        set { __pbn__SecondTarget = value; }
    }
    public bool ShouldSerializeSecondTarget() => __pbn__SecondTarget != null;
    public void ResetSecondTarget() => __pbn__SecondTarget = null;
    private int? __pbn__SecondTarget;

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_DesiredTimescale")]
public partial class CCSUsrMsgDesiredTimescale : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"desired_timescale")]
    public float DesiredTimescale
    {
        get { return __pbn__DesiredTimescale.GetValueOrDefault(); }
        set { __pbn__DesiredTimescale = value; }
    }
    public bool ShouldSerializeDesiredTimescale() => __pbn__DesiredTimescale != null;
    public void ResetDesiredTimescale() => __pbn__DesiredTimescale = null;
    private float? __pbn__DesiredTimescale;

    [global::ProtoBuf.ProtoMember(2, Name = @"duration_realtime_sec")]
    public float DurationRealtimeSec
    {
        get { return __pbn__DurationRealtimeSec.GetValueOrDefault(); }
        set { __pbn__DurationRealtimeSec = value; }
    }
    public bool ShouldSerializeDurationRealtimeSec() => __pbn__DurationRealtimeSec != null;
    public void ResetDurationRealtimeSec() => __pbn__DurationRealtimeSec = null;
    private float? __pbn__DurationRealtimeSec;

    [global::ProtoBuf.ProtoMember(3, Name = @"interpolator_type")]
    public int InterpolatorType
    {
        get { return __pbn__InterpolatorType.GetValueOrDefault(); }
        set { __pbn__InterpolatorType = value; }
    }
    public bool ShouldSerializeInterpolatorType() => __pbn__InterpolatorType != null;
    public void ResetInterpolatorType() => __pbn__InterpolatorType = null;
    private int? __pbn__InterpolatorType;

    [global::ProtoBuf.ProtoMember(4, Name = @"start_blend_time")]
    public float StartBlendTime
    {
        get { return __pbn__StartBlendTime.GetValueOrDefault(); }
        set { __pbn__StartBlendTime = value; }
    }
    public bool ShouldSerializeStartBlendTime() => __pbn__StartBlendTime != null;
    public void ResetStartBlendTime() => __pbn__StartBlendTime = null;
    private float? __pbn__StartBlendTime;

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_CurrentTimescale")]
public partial class CCSUsrMsgCurrentTimescale : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"cur_timescale")]
    public float CurTimescale
    {
        get { return __pbn__CurTimescale.GetValueOrDefault(); }
        set { __pbn__CurTimescale = value; }
    }
    public bool ShouldSerializeCurTimescale() => __pbn__CurTimescale != null;
    public void ResetCurTimescale() => __pbn__CurTimescale = null;
    private float? __pbn__CurTimescale;

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_AchievementEvent")]
public partial class CCSUsrMsgAchievementEvent : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"achievement")]
    public int Achievement
    {
        get { return __pbn__Achievement.GetValueOrDefault(); }
        set { __pbn__Achievement = value; }
    }
    public bool ShouldSerializeAchievement() => __pbn__Achievement != null;
    public void ResetAchievement() => __pbn__Achievement = null;
    private int? __pbn__Achievement;

    [global::ProtoBuf.ProtoMember(2, Name = @"count")]
    public int Count
    {
        get { return __pbn__Count.GetValueOrDefault(); }
        set { __pbn__Count = value; }
    }
    public bool ShouldSerializeCount() => __pbn__Count != null;
    public void ResetCount() => __pbn__Count = null;
    private int? __pbn__Count;

    [global::ProtoBuf.ProtoMember(3, Name = @"user_id")]
    public int UserId
    {
        get { return __pbn__UserId.GetValueOrDefault(); }
        set { __pbn__UserId = value; }
    }
    public bool ShouldSerializeUserId() => __pbn__UserId != null;
    public void ResetUserId() => __pbn__UserId = null;
    private int? __pbn__UserId;

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_MatchEndConditions")]
public partial class CCSUsrMsgMatchEndConditions : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"fraglimit")]
    public int Fraglimit
    {
        get { return __pbn__Fraglimit.GetValueOrDefault(); }
        set { __pbn__Fraglimit = value; }
    }
    public bool ShouldSerializeFraglimit() => __pbn__Fraglimit != null;
    public void ResetFraglimit() => __pbn__Fraglimit = null;
    private int? __pbn__Fraglimit;

    [global::ProtoBuf.ProtoMember(2, Name = @"mp_maxrounds")]
    public int MpMaxrounds
    {
        get { return __pbn__MpMaxrounds.GetValueOrDefault(); }
        set { __pbn__MpMaxrounds = value; }
    }
    public bool ShouldSerializeMpMaxrounds() => __pbn__MpMaxrounds != null;
    public void ResetMpMaxrounds() => __pbn__MpMaxrounds = null;
    private int? __pbn__MpMaxrounds;

    [global::ProtoBuf.ProtoMember(3, Name = @"mp_winlimit")]
    public int MpWinlimit
    {
        get { return __pbn__MpWinlimit.GetValueOrDefault(); }
        set { __pbn__MpWinlimit = value; }
    }
    public bool ShouldSerializeMpWinlimit() => __pbn__MpWinlimit != null;
    public void ResetMpWinlimit() => __pbn__MpWinlimit = null;
    private int? __pbn__MpWinlimit;

    [global::ProtoBuf.ProtoMember(4, Name = @"mp_timelimit")]
    public int MpTimelimit
    {
        get { return __pbn__MpTimelimit.GetValueOrDefault(); }
        set { __pbn__MpTimelimit = value; }
    }
    public bool ShouldSerializeMpTimelimit() => __pbn__MpTimelimit != null;
    public void ResetMpTimelimit() => __pbn__MpTimelimit = null;
    private int? __pbn__MpTimelimit;

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_DisplayInventory")]
public partial class CCSUsrMsgDisplayInventory : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"display")]
    public bool Display
    {
        get { return __pbn__Display.GetValueOrDefault(); }
        set { __pbn__Display = value; }
    }
    public bool ShouldSerializeDisplay() => __pbn__Display != null;
    public void ResetDisplay() => __pbn__Display = null;
    private bool? __pbn__Display;

    [global::ProtoBuf.ProtoMember(2, Name = @"user_id")]
    public int UserId
    {
        get { return __pbn__UserId.GetValueOrDefault(); }
        set { __pbn__UserId = value; }
    }
    public bool ShouldSerializeUserId() => __pbn__UserId != null;
    public void ResetUserId() => __pbn__UserId = null;
    private int? __pbn__UserId;

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_CallVoteFailed")]
public partial class CCSUsrMsgCallVoteFailed : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"reason")]
    public int Reason
    {
        get { return __pbn__Reason.GetValueOrDefault(); }
        set { __pbn__Reason = value; }
    }
    public bool ShouldSerializeReason() => __pbn__Reason != null;
    public void ResetReason() => __pbn__Reason = null;
    private int? __pbn__Reason;

    [global::ProtoBuf.ProtoMember(2, Name = @"time")]
    public int Time
    {
        get { return __pbn__Time.GetValueOrDefault(); }
        set { __pbn__Time = value; }
    }
    public bool ShouldSerializeTime() => __pbn__Time != null;
    public void ResetTime() => __pbn__Time = null;
    private int? __pbn__Time;

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_VoteStart")]
public partial class CCSUsrMsgVoteStart : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"team")]
    public int Team
    {
        get { return __pbn__Team.GetValueOrDefault(); }
        set { __pbn__Team = value; }
    }
    public bool ShouldSerializeTeam() => __pbn__Team != null;
    public void ResetTeam() => __pbn__Team = null;
    private int? __pbn__Team;

    [global::ProtoBuf.ProtoMember(2, Name = @"ent_idx")]
    public int EntIdx
    {
        get { return __pbn__EntIdx.GetValueOrDefault(); }
        set { __pbn__EntIdx = value; }
    }
    public bool ShouldSerializeEntIdx() => __pbn__EntIdx != null;
    public void ResetEntIdx() => __pbn__EntIdx = null;
    private int? __pbn__EntIdx;

    [global::ProtoBuf.ProtoMember(3, Name = @"vote_type")]
    public int VoteType
    {
        get { return __pbn__VoteType.GetValueOrDefault(); }
        set { __pbn__VoteType = value; }
    }
    public bool ShouldSerializeVoteType() => __pbn__VoteType != null;
    public void ResetVoteType() => __pbn__VoteType = null;
    private int? __pbn__VoteType;

    [global::ProtoBuf.ProtoMember(4, Name = @"disp_str")]
    [global::System.ComponentModel.DefaultValue("")]
    public string DispStr
    {
        get { return __pbn__DispStr ?? ""; }
        set { __pbn__DispStr = value; }
    }
    public bool ShouldSerializeDispStr() => __pbn__DispStr != null;
    public void ResetDispStr() => __pbn__DispStr = null;
    private string __pbn__DispStr;

    [global::ProtoBuf.ProtoMember(5, Name = @"details_str")]
    [global::System.ComponentModel.DefaultValue("")]
    public string DetailsStr
    {
        get { return __pbn__DetailsStr ?? ""; }
        set { __pbn__DetailsStr = value; }
    }
    public bool ShouldSerializeDetailsStr() => __pbn__DetailsStr != null;
    public void ResetDetailsStr() => __pbn__DetailsStr = null;
    private string __pbn__DetailsStr;

    [global::ProtoBuf.ProtoMember(6, Name = @"other_team_str")]
    [global::System.ComponentModel.DefaultValue("")]
    public string OtherTeamStr
    {
        get { return __pbn__OtherTeamStr ?? ""; }
        set { __pbn__OtherTeamStr = value; }
    }
    public bool ShouldSerializeOtherTeamStr() => __pbn__OtherTeamStr != null;
    public void ResetOtherTeamStr() => __pbn__OtherTeamStr = null;
    private string __pbn__OtherTeamStr;

    [global::ProtoBuf.ProtoMember(7, Name = @"is_yes_no_vote")]
    public bool IsYesNoVote
    {
        get { return __pbn__IsYesNoVote.GetValueOrDefault(); }
        set { __pbn__IsYesNoVote = value; }
    }
    public bool ShouldSerializeIsYesNoVote() => __pbn__IsYesNoVote != null;
    public void ResetIsYesNoVote() => __pbn__IsYesNoVote = null;
    private bool? __pbn__IsYesNoVote;

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_VotePass")]
public partial class CCSUsrMsgVotePass : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"team")]
    public int Team
    {
        get { return __pbn__Team.GetValueOrDefault(); }
        set { __pbn__Team = value; }
    }
    public bool ShouldSerializeTeam() => __pbn__Team != null;
    public void ResetTeam() => __pbn__Team = null;
    private int? __pbn__Team;

    [global::ProtoBuf.ProtoMember(2, Name = @"vote_type")]
    public int VoteType
    {
        get { return __pbn__VoteType.GetValueOrDefault(); }
        set { __pbn__VoteType = value; }
    }
    public bool ShouldSerializeVoteType() => __pbn__VoteType != null;
    public void ResetVoteType() => __pbn__VoteType = null;
    private int? __pbn__VoteType;

    [global::ProtoBuf.ProtoMember(3, Name = @"disp_str")]
    [global::System.ComponentModel.DefaultValue("")]
    public string DispStr
    {
        get { return __pbn__DispStr ?? ""; }
        set { __pbn__DispStr = value; }
    }
    public bool ShouldSerializeDispStr() => __pbn__DispStr != null;
    public void ResetDispStr() => __pbn__DispStr = null;
    private string __pbn__DispStr;

    [global::ProtoBuf.ProtoMember(4, Name = @"details_str")]
    [global::System.ComponentModel.DefaultValue("")]
    public string DetailsStr
    {
        get { return __pbn__DetailsStr ?? ""; }
        set { __pbn__DetailsStr = value; }
    }
    public bool ShouldSerializeDetailsStr() => __pbn__DetailsStr != null;
    public void ResetDetailsStr() => __pbn__DetailsStr = null;
    private string __pbn__DetailsStr;

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_VoteFailed")]
public partial class CCSUsrMsgVoteFailed : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"team")]
    public int Team
    {
        get { return __pbn__Team.GetValueOrDefault(); }
        set { __pbn__Team = value; }
    }
    public bool ShouldSerializeTeam() => __pbn__Team != null;
    public void ResetTeam() => __pbn__Team = null;
    private int? __pbn__Team;

    [global::ProtoBuf.ProtoMember(2, Name = @"reason")]
    public int Reason
    {
        get { return __pbn__Reason.GetValueOrDefault(); }
        set { __pbn__Reason = value; }
    }
    public bool ShouldSerializeReason() => __pbn__Reason != null;
    public void ResetReason() => __pbn__Reason = null;
    private int? __pbn__Reason;

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_VoteSetup")]
public partial class CCSUsrMsgVoteSetup : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"potential_issues")]
    public global::System.Collections.Generic.List<string> PotentialIssues { get; } = new global::System.Collections.Generic.List<string>();

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_SendLastKillerDamageToClient")]
public partial class CCSUsrMsgSendLastKillerDamageToClient : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"num_hits_given")]
    public int NumHitsGiven
    {
        get { return __pbn__NumHitsGiven.GetValueOrDefault(); }
        set { __pbn__NumHitsGiven = value; }
    }
    public bool ShouldSerializeNumHitsGiven() => __pbn__NumHitsGiven != null;
    public void ResetNumHitsGiven() => __pbn__NumHitsGiven = null;
    private int? __pbn__NumHitsGiven;

    [global::ProtoBuf.ProtoMember(2, Name = @"damage_given")]
    public int DamageGiven
    {
        get { return __pbn__DamageGiven.GetValueOrDefault(); }
        set { __pbn__DamageGiven = value; }
    }
    public bool ShouldSerializeDamageGiven() => __pbn__DamageGiven != null;
    public void ResetDamageGiven() => __pbn__DamageGiven = null;
    private int? __pbn__DamageGiven;

    [global::ProtoBuf.ProtoMember(3, Name = @"num_hits_taken")]
    public int NumHitsTaken
    {
        get { return __pbn__NumHitsTaken.GetValueOrDefault(); }
        set { __pbn__NumHitsTaken = value; }
    }
    public bool ShouldSerializeNumHitsTaken() => __pbn__NumHitsTaken != null;
    public void ResetNumHitsTaken() => __pbn__NumHitsTaken = null;
    private int? __pbn__NumHitsTaken;

    [global::ProtoBuf.ProtoMember(4, Name = @"damage_taken")]
    public int DamageTaken
    {
        get { return __pbn__DamageTaken.GetValueOrDefault(); }
        set { __pbn__DamageTaken = value; }
    }
    public bool ShouldSerializeDamageTaken() => __pbn__DamageTaken != null;
    public void ResetDamageTaken() => __pbn__DamageTaken = null;
    private int? __pbn__DamageTaken;

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_ItemPickup")]
public partial class CCSUsrMsgItemPickup : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"item")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Item
    {
        get { return __pbn__Item ?? ""; }
        set { __pbn__Item = value; }
    }
    public bool ShouldSerializeItem() => __pbn__Item != null;
    public void ResetItem() => __pbn__Item = null;
    private string __pbn__Item;

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_ShowMenu")]
public partial class CCSUsrMsgShowMenu : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"bits_valid_slots")]
    public int BitsValidSlots
    {
        get { return __pbn__BitsValidSlots.GetValueOrDefault(); }
        set { __pbn__BitsValidSlots = value; }
    }
    public bool ShouldSerializeBitsValidSlots() => __pbn__BitsValidSlots != null;
    public void ResetBitsValidSlots() => __pbn__BitsValidSlots = null;
    private int? __pbn__BitsValidSlots;

    [global::ProtoBuf.ProtoMember(2, Name = @"display_time")]
    public int DisplayTime
    {
        get { return __pbn__DisplayTime.GetValueOrDefault(); }
        set { __pbn__DisplayTime = value; }
    }
    public bool ShouldSerializeDisplayTime() => __pbn__DisplayTime != null;
    public void ResetDisplayTime() => __pbn__DisplayTime = null;
    private int? __pbn__DisplayTime;

    [global::ProtoBuf.ProtoMember(3, Name = @"menu_string")]
    [global::System.ComponentModel.DefaultValue("")]
    public string MenuString
    {
        get { return __pbn__MenuString ?? ""; }
        set { __pbn__MenuString = value; }
    }
    public bool ShouldSerializeMenuString() => __pbn__MenuString != null;
    public void ResetMenuString() => __pbn__MenuString = null;
    private string __pbn__MenuString;

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_BarTime")]
public partial class CCSUsrMsgBarTime : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"time")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Time
    {
        get { return __pbn__Time ?? ""; }
        set { __pbn__Time = value; }
    }
    public bool ShouldSerializeTime() => __pbn__Time != null;
    public void ResetTime() => __pbn__Time = null;
    private string __pbn__Time;

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_AmmoDenied")]
public partial class CCSUsrMsgAmmoDenied : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public int ammoIdx
    {
        get { return __pbn__ammoIdx.GetValueOrDefault(); }
        set { __pbn__ammoIdx = value; }
    }
    public bool ShouldSerializeammoIdx() => __pbn__ammoIdx != null;
    public void ResetammoIdx() => __pbn__ammoIdx = null;
    private int? __pbn__ammoIdx;

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_MarkAchievement")]
public partial class CCSUsrMsgMarkAchievement : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"achievement")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Achievement
    {
        get { return __pbn__Achievement ?? ""; }
        set { __pbn__Achievement = value; }
    }
    public bool ShouldSerializeAchievement() => __pbn__Achievement != null;
    public void ResetAchievement() => __pbn__Achievement = null;
    private string __pbn__Achievement;

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_ItemDrop")]
public partial class CCSUsrMsgItemDrop : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"itemid")]
    public long Itemid
    {
        get { return __pbn__Itemid.GetValueOrDefault(); }
        set { __pbn__Itemid = value; }
    }
    public bool ShouldSerializeItemid() => __pbn__Itemid != null;
    public void ResetItemid() => __pbn__Itemid = null;
    private long? __pbn__Itemid;

    [global::ProtoBuf.ProtoMember(2, Name = @"death")]
    public bool Death
    {
        get { return __pbn__Death.GetValueOrDefault(); }
        set { __pbn__Death = value; }
    }
    public bool ShouldSerializeDeath() => __pbn__Death != null;
    public void ResetDeath() => __pbn__Death = null;
    private bool? __pbn__Death;

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_GlowPropTurnOff")]
public partial class CCSUsrMsgGlowPropTurnOff : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"entidx")]
    public int Entidx
    {
        get { return __pbn__Entidx.GetValueOrDefault(); }
        set { __pbn__Entidx = value; }
    }
    public bool ShouldSerializeEntidx() => __pbn__Entidx != null;
    public void ResetEntidx() => __pbn__Entidx = null;
    private int? __pbn__Entidx;

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_RoundBackupFilenames")]
public partial class CCSUsrMsgRoundBackupFilenames : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"count")]
    public int Count
    {
        get { return __pbn__Count.GetValueOrDefault(); }
        set { __pbn__Count = value; }
    }
    public bool ShouldSerializeCount() => __pbn__Count != null;
    public void ResetCount() => __pbn__Count = null;
    private int? __pbn__Count;

    [global::ProtoBuf.ProtoMember(2, Name = @"index")]
    public int Index
    {
        get { return __pbn__Index.GetValueOrDefault(); }
        set { __pbn__Index = value; }
    }
    public bool ShouldSerializeIndex() => __pbn__Index != null;
    public void ResetIndex() => __pbn__Index = null;
    private int? __pbn__Index;

    [global::ProtoBuf.ProtoMember(3, Name = @"filename")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Filename
    {
        get { return __pbn__Filename ?? ""; }
        set { __pbn__Filename = value; }
    }
    public bool ShouldSerializeFilename() => __pbn__Filename != null;
    public void ResetFilename() => __pbn__Filename = null;
    private string __pbn__Filename;

    [global::ProtoBuf.ProtoMember(4, Name = @"nicename")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Nicename
    {
        get { return __pbn__Nicename ?? ""; }
        set { __pbn__Nicename = value; }
    }
    public bool ShouldSerializeNicename() => __pbn__Nicename != null;
    public void ResetNicename() => __pbn__Nicename = null;
    private string __pbn__Nicename;

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_ResetHud")]
public partial class CCSUsrMsgResetHud : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"reset")]
    public bool Reset
    {
        get { return __pbn__Reset.GetValueOrDefault(); }
        set { __pbn__Reset = value; }
    }
    public bool ShouldSerializeReset() => __pbn__Reset != null;
    public void ResetReset() => __pbn__Reset = null;
    private bool? __pbn__Reset;

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_GameTitle")]
public partial class CCSUsrMsgGameTitle : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"dummy")]
    public int Dummy
    {
        get { return __pbn__Dummy.GetValueOrDefault(); }
        set { __pbn__Dummy = value; }
    }
    public bool ShouldSerializeDummy() => __pbn__Dummy != null;
    public void ResetDummy() => __pbn__Dummy = null;
    private int? __pbn__Dummy;

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_RequestState")]
public partial class CCSUsrMsgRequestState : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"dummy")]
    public int Dummy
    {
        get { return __pbn__Dummy.GetValueOrDefault(); }
        set { __pbn__Dummy = value; }
    }
    public bool ShouldSerializeDummy() => __pbn__Dummy != null;
    public void ResetDummy() => __pbn__Dummy = null;
    private int? __pbn__Dummy;

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_StopSpectatorMode")]
public partial class CCSUsrMsgStopSpectatorMode : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"dummy")]
    public int Dummy
    {
        get { return __pbn__Dummy.GetValueOrDefault(); }
        set { __pbn__Dummy = value; }
    }
    public bool ShouldSerializeDummy() => __pbn__Dummy != null;
    public void ResetDummy() => __pbn__Dummy = null;
    private int? __pbn__Dummy;

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_DisconnectToLobby")]
public partial class CCSUsrMsgDisconnectToLobby : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"dummy")]
    public int Dummy
    {
        get { return __pbn__Dummy.GetValueOrDefault(); }
        set { __pbn__Dummy = value; }
    }
    public bool ShouldSerializeDummy() => __pbn__Dummy != null;
    public void ResetDummy() => __pbn__Dummy = null;
    private int? __pbn__Dummy;

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_WarmupHasEnded")]
public partial class CCSUsrMsgWarmupHasEnded : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"dummy")]
    public int Dummy
    {
        get { return __pbn__Dummy.GetValueOrDefault(); }
        set { __pbn__Dummy = value; }
    }
    public bool ShouldSerializeDummy() => __pbn__Dummy != null;
    public void ResetDummy() => __pbn__Dummy = null;
    private int? __pbn__Dummy;

}

[global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_ClientInfo")]
public partial class CCSUsrMsgClientInfo : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"dummy")]
    public int Dummy
    {
        get { return __pbn__Dummy.GetValueOrDefault(); }
        set { __pbn__Dummy = value; }
    }
    public bool ShouldSerializeDummy() => __pbn__Dummy != null;
    public void ResetDummy() => __pbn__Dummy = null;
    private int? __pbn__Dummy;

}

[global::ProtoBuf.ProtoContract()]
public enum ECstrike15UserMessages
{
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_VGUIMenu")]
    CSUMVGUIMenu = 1,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_Geiger")]
    CSUMGeiger = 2,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_Train")]
    CSUMTrain = 3,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_HudText")]
    CSUMHudText = 4,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_SayText")]
    CSUMSayText = 5,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_SayText2")]
    CSUMSayText2 = 6,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_TextMsg")]
    CSUMTextMsg = 7,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_HudMsg")]
    CSUMHudMsg = 8,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_ResetHud")]
    CSUMResetHud = 9,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_GameTitle")]
    CSUMGameTitle = 10,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_Shake")]
    CSUMShake = 12,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_Fade")]
    CSUMFade = 13,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_Rumble")]
    CSUMRumble = 14,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_CloseCaption")]
    CSUMCloseCaption = 15,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_CloseCaptionDirect")]
    CSUMCloseCaptionDirect = 16,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_SendAudio")]
    CSUMSendAudio = 17,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_RawAudio")]
    CSUMRawAudio = 18,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_VoiceMask")]
    CSUMVoiceMask = 19,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_RequestState")]
    CSUMRequestState = 20,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_Damage")]
    CSUMDamage = 21,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_RadioText")]
    CSUMRadioText = 22,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_HintText")]
    CSUMHintText = 23,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_KeyHintText")]
    CSUMKeyHintText = 24,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_ProcessSpottedEntityUpdate")]
    CSUMProcessSpottedEntityUpdate = 25,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_ReloadEffect")]
    CSUMReloadEffect = 26,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_AdjustMoney")]
    CSUMAdjustMoney = 27,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_UpdateTeamMoney")]
    CSUMUpdateTeamMoney = 28,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_StopSpectatorMode")]
    CSUMStopSpectatorMode = 29,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_KillCam")]
    CSUMKillCam = 30,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_DesiredTimescale")]
    CSUMDesiredTimescale = 31,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_CurrentTimescale")]
    CSUMCurrentTimescale = 32,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_AchievementEvent")]
    CSUMAchievementEvent = 33,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_MatchEndConditions")]
    CSUMMatchEndConditions = 34,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_DisconnectToLobby")]
    CSUMDisconnectToLobby = 35,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_DisplayInventory")]
    CSUMDisplayInventory = 37,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_WarmupHasEnded")]
    CSUMWarmupHasEnded = 38,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_ClientInfo")]
    CSUMClientInfo = 39,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_CallVoteFailed")]
    CSUMCallVoteFailed = 45,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_VoteStart")]
    CSUMVoteStart = 46,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_VotePass")]
    CSUMVotePass = 47,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_VoteFailed")]
    CSUMVoteFailed = 48,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_VoteSetup")]
    CSUMVoteSetup = 49,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_SendLastKillerDamageToClient")]
    CSUMSendLastKillerDamageToClient = 51,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_ItemPickup")]
    CSUMItemPickup = 53,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_ShowMenu")]
    CSUMShowMenu = 54,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_BarTime")]
    CSUMBarTime = 55,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_AmmoDenied")]
    CSUMAmmoDenied = 56,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_MarkAchievement")]
    CSUMMarkAchievement = 57,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_ItemDrop")]
    CSUMItemDrop = 59,
    [global::ProtoBuf.ProtoEnum(Name = @"CS_UM_GlowPropTurnOff")]
    CSUMGlowPropTurnOff = 60,
}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
