// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: netmessages_public.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
[global::ProtoBuf.ProtoContract()]
public partial class CMsgVector : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"x")]
    public float X
    {
        get { return __pbn__X.GetValueOrDefault(); }
        set { __pbn__X = value; }
    }
    public bool ShouldSerializeX() => __pbn__X != null;
    public void ResetX() => __pbn__X = null;
    private float? __pbn__X;

    [global::ProtoBuf.ProtoMember(2, Name = @"y")]
    public float Y
    {
        get { return __pbn__Y.GetValueOrDefault(); }
        set { __pbn__Y = value; }
    }
    public bool ShouldSerializeY() => __pbn__Y != null;
    public void ResetY() => __pbn__Y = null;
    private float? __pbn__Y;

    [global::ProtoBuf.ProtoMember(3, Name = @"z")]
    public float Z
    {
        get { return __pbn__Z.GetValueOrDefault(); }
        set { __pbn__Z = value; }
    }
    public bool ShouldSerializeZ() => __pbn__Z != null;
    public void ResetZ() => __pbn__Z = null;
    private float? __pbn__Z;

}

[global::ProtoBuf.ProtoContract()]
public partial class CMsgVector2D : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"x")]
    public float X
    {
        get { return __pbn__X.GetValueOrDefault(); }
        set { __pbn__X = value; }
    }
    public bool ShouldSerializeX() => __pbn__X != null;
    public void ResetX() => __pbn__X = null;
    private float? __pbn__X;

    [global::ProtoBuf.ProtoMember(2, Name = @"y")]
    public float Y
    {
        get { return __pbn__Y.GetValueOrDefault(); }
        set { __pbn__Y = value; }
    }
    public bool ShouldSerializeY() => __pbn__Y != null;
    public void ResetY() => __pbn__Y = null;
    private float? __pbn__Y;

}

[global::ProtoBuf.ProtoContract()]
public partial class CMsgQAngle : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"x")]
    public float X
    {
        get { return __pbn__X.GetValueOrDefault(); }
        set { __pbn__X = value; }
    }
    public bool ShouldSerializeX() => __pbn__X != null;
    public void ResetX() => __pbn__X = null;
    private float? __pbn__X;

    [global::ProtoBuf.ProtoMember(2, Name = @"y")]
    public float Y
    {
        get { return __pbn__Y.GetValueOrDefault(); }
        set { __pbn__Y = value; }
    }
    public bool ShouldSerializeY() => __pbn__Y != null;
    public void ResetY() => __pbn__Y = null;
    private float? __pbn__Y;

    [global::ProtoBuf.ProtoMember(3, Name = @"z")]
    public float Z
    {
        get { return __pbn__Z.GetValueOrDefault(); }
        set { __pbn__Z = value; }
    }
    public bool ShouldSerializeZ() => __pbn__Z != null;
    public void ResetZ() => __pbn__Z = null;
    private float? __pbn__Z;

}

[global::ProtoBuf.ProtoContract()]
public partial class CMsgRGBA : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"r")]
    public int R
    {
        get { return __pbn__R.GetValueOrDefault(); }
        set { __pbn__R = value; }
    }
    public bool ShouldSerializeR() => __pbn__R != null;
    public void ResetR() => __pbn__R = null;
    private int? __pbn__R;

    [global::ProtoBuf.ProtoMember(2, Name = @"g")]
    public int G
    {
        get { return __pbn__G.GetValueOrDefault(); }
        set { __pbn__G = value; }
    }
    public bool ShouldSerializeG() => __pbn__G != null;
    public void ResetG() => __pbn__G = null;
    private int? __pbn__G;

    [global::ProtoBuf.ProtoMember(3, Name = @"b")]
    public int B
    {
        get { return __pbn__B.GetValueOrDefault(); }
        set { __pbn__B = value; }
    }
    public bool ShouldSerializeB() => __pbn__B != null;
    public void ResetB() => __pbn__B = null;
    private int? __pbn__B;

    [global::ProtoBuf.ProtoMember(4, Name = @"a")]
    public int A
    {
        get { return __pbn__A.GetValueOrDefault(); }
        set { __pbn__A = value; }
    }
    public bool ShouldSerializeA() => __pbn__A != null;
    public void ResetA() => __pbn__A = null;
    private int? __pbn__A;

}

[global::ProtoBuf.ProtoContract(Name = @"CNETMsg_Tick")]
public partial class CNETMsgTick : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"tick")]
    public uint Tick
    {
        get { return __pbn__Tick.GetValueOrDefault(); }
        set { __pbn__Tick = value; }
    }
    public bool ShouldSerializeTick() => __pbn__Tick != null;
    public void ResetTick() => __pbn__Tick = null;
    private uint? __pbn__Tick;

    [global::ProtoBuf.ProtoMember(4, Name = @"host_computationtime")]
    public uint HostComputationtime
    {
        get { return __pbn__HostComputationtime.GetValueOrDefault(); }
        set { __pbn__HostComputationtime = value; }
    }
    public bool ShouldSerializeHostComputationtime() => __pbn__HostComputationtime != null;
    public void ResetHostComputationtime() => __pbn__HostComputationtime = null;
    private uint? __pbn__HostComputationtime;

    [global::ProtoBuf.ProtoMember(5, Name = @"host_computationtime_std_deviation")]
    public uint HostComputationtimeStdDeviation
    {
        get { return __pbn__HostComputationtimeStdDeviation.GetValueOrDefault(); }
        set { __pbn__HostComputationtimeStdDeviation = value; }
    }
    public bool ShouldSerializeHostComputationtimeStdDeviation() => __pbn__HostComputationtimeStdDeviation != null;
    public void ResetHostComputationtimeStdDeviation() => __pbn__HostComputationtimeStdDeviation = null;
    private uint? __pbn__HostComputationtimeStdDeviation;

    [global::ProtoBuf.ProtoMember(6, Name = @"host_framestarttime_std_deviation")]
    public uint HostFramestarttimeStdDeviation
    {
        get { return __pbn__HostFramestarttimeStdDeviation.GetValueOrDefault(); }
        set { __pbn__HostFramestarttimeStdDeviation = value; }
    }
    public bool ShouldSerializeHostFramestarttimeStdDeviation() => __pbn__HostFramestarttimeStdDeviation != null;
    public void ResetHostFramestarttimeStdDeviation() => __pbn__HostFramestarttimeStdDeviation = null;
    private uint? __pbn__HostFramestarttimeStdDeviation;

}

[global::ProtoBuf.ProtoContract(Name = @"CNETMsg_StringCmd")]
public partial class CNETMsgStringCmd : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"command")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Command
    {
        get { return __pbn__Command ?? ""; }
        set { __pbn__Command = value; }
    }
    public bool ShouldSerializeCommand() => __pbn__Command != null;
    public void ResetCommand() => __pbn__Command = null;
    private string __pbn__Command;

}

[global::ProtoBuf.ProtoContract(Name = @"CNETMsg_SignonState")]
public partial class CNETMsgSignonState : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"signon_state")]
    public uint SignonState
    {
        get { return __pbn__SignonState.GetValueOrDefault(); }
        set { __pbn__SignonState = value; }
    }
    public bool ShouldSerializeSignonState() => __pbn__SignonState != null;
    public void ResetSignonState() => __pbn__SignonState = null;
    private uint? __pbn__SignonState;

    [global::ProtoBuf.ProtoMember(2, Name = @"spawn_count")]
    public uint SpawnCount
    {
        get { return __pbn__SpawnCount.GetValueOrDefault(); }
        set { __pbn__SpawnCount = value; }
    }
    public bool ShouldSerializeSpawnCount() => __pbn__SpawnCount != null;
    public void ResetSpawnCount() => __pbn__SpawnCount = null;
    private uint? __pbn__SpawnCount;

    [global::ProtoBuf.ProtoMember(3, Name = @"num_server_players")]
    public uint NumServerPlayers
    {
        get { return __pbn__NumServerPlayers.GetValueOrDefault(); }
        set { __pbn__NumServerPlayers = value; }
    }
    public bool ShouldSerializeNumServerPlayers() => __pbn__NumServerPlayers != null;
    public void ResetNumServerPlayers() => __pbn__NumServerPlayers = null;
    private uint? __pbn__NumServerPlayers;

    [global::ProtoBuf.ProtoMember(4, Name = @"players_networkids")]
    public global::System.Collections.Generic.List<string> PlayersNetworkids { get; } = new global::System.Collections.Generic.List<string>();

    [global::ProtoBuf.ProtoMember(5, Name = @"map_name")]
    [global::System.ComponentModel.DefaultValue("")]
    public string MapName
    {
        get { return __pbn__MapName ?? ""; }
        set { __pbn__MapName = value; }
    }
    public bool ShouldSerializeMapName() => __pbn__MapName != null;
    public void ResetMapName() => __pbn__MapName = null;
    private string __pbn__MapName;

}

[global::ProtoBuf.ProtoContract(Name = @"CMsg_CVars")]
public partial class CMsgCVars : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"cvars")]
    public global::System.Collections.Generic.List<CVar> Cvars { get; } = new global::System.Collections.Generic.List<CVar>();

    [global::ProtoBuf.ProtoContract()]
    public partial class CVar : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get { return __pbn__Name ?? ""; }
            set { __pbn__Name = value; }
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(2, Name = @"value")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Value
        {
            get { return __pbn__Value ?? ""; }
            set { __pbn__Value = value; }
        }
        public bool ShouldSerializeValue() => __pbn__Value != null;
        public void ResetValue() => __pbn__Value = null;
        private string __pbn__Value;

    }

}

[global::ProtoBuf.ProtoContract(Name = @"CNETMsg_SetConVar")]
public partial class CNETMsgSetConVar : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"convars")]
    public CMsgCVars Convars { get; set; }

}

[global::ProtoBuf.ProtoContract(Name = @"CNETMsg_NOP")]
public partial class CNETMsgNOP : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

}

[global::ProtoBuf.ProtoContract(Name = @"CNETMsg_Disconnect")]
public partial class CNETMsgDisconnect : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"text")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Text
    {
        get { return __pbn__Text ?? ""; }
        set { __pbn__Text = value; }
    }
    public bool ShouldSerializeText() => __pbn__Text != null;
    public void ResetText() => __pbn__Text = null;
    private string __pbn__Text;

}

[global::ProtoBuf.ProtoContract(Name = @"CNETMsg_File")]
public partial class CNETMsgFile : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"transfer_id")]
    public int TransferId
    {
        get { return __pbn__TransferId.GetValueOrDefault(); }
        set { __pbn__TransferId = value; }
    }
    public bool ShouldSerializeTransferId() => __pbn__TransferId != null;
    public void ResetTransferId() => __pbn__TransferId = null;
    private int? __pbn__TransferId;

    [global::ProtoBuf.ProtoMember(2, Name = @"file_name")]
    [global::System.ComponentModel.DefaultValue("")]
    public string FileName
    {
        get { return __pbn__FileName ?? ""; }
        set { __pbn__FileName = value; }
    }
    public bool ShouldSerializeFileName() => __pbn__FileName != null;
    public void ResetFileName() => __pbn__FileName = null;
    private string __pbn__FileName;

    [global::ProtoBuf.ProtoMember(3, Name = @"is_replay_demo_file")]
    public bool IsReplayDemoFile
    {
        get { return __pbn__IsReplayDemoFile.GetValueOrDefault(); }
        set { __pbn__IsReplayDemoFile = value; }
    }
    public bool ShouldSerializeIsReplayDemoFile() => __pbn__IsReplayDemoFile != null;
    public void ResetIsReplayDemoFile() => __pbn__IsReplayDemoFile = null;
    private bool? __pbn__IsReplayDemoFile;

    [global::ProtoBuf.ProtoMember(4, Name = @"deny")]
    public bool Deny
    {
        get { return __pbn__Deny.GetValueOrDefault(); }
        set { __pbn__Deny = value; }
    }
    public bool ShouldSerializeDeny() => __pbn__Deny != null;
    public void ResetDeny() => __pbn__Deny = null;
    private bool? __pbn__Deny;

}

[global::ProtoBuf.ProtoContract(Name = @"CSVCMsg_ServerInfo")]
public partial class CSVCMsgServerInfo : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"protocol")]
    public int Protocol
    {
        get { return __pbn__Protocol.GetValueOrDefault(); }
        set { __pbn__Protocol = value; }
    }
    public bool ShouldSerializeProtocol() => __pbn__Protocol != null;
    public void ResetProtocol() => __pbn__Protocol = null;
    private int? __pbn__Protocol;

    [global::ProtoBuf.ProtoMember(2, Name = @"server_count")]
    public int ServerCount
    {
        get { return __pbn__ServerCount.GetValueOrDefault(); }
        set { __pbn__ServerCount = value; }
    }
    public bool ShouldSerializeServerCount() => __pbn__ServerCount != null;
    public void ResetServerCount() => __pbn__ServerCount = null;
    private int? __pbn__ServerCount;

    [global::ProtoBuf.ProtoMember(3, Name = @"is_dedicated")]
    public bool IsDedicated
    {
        get { return __pbn__IsDedicated.GetValueOrDefault(); }
        set { __pbn__IsDedicated = value; }
    }
    public bool ShouldSerializeIsDedicated() => __pbn__IsDedicated != null;
    public void ResetIsDedicated() => __pbn__IsDedicated = null;
    private bool? __pbn__IsDedicated;

    [global::ProtoBuf.ProtoMember(4, Name = @"is_official_valve_server")]
    public bool IsOfficialValveServer
    {
        get { return __pbn__IsOfficialValveServer.GetValueOrDefault(); }
        set { __pbn__IsOfficialValveServer = value; }
    }
    public bool ShouldSerializeIsOfficialValveServer() => __pbn__IsOfficialValveServer != null;
    public void ResetIsOfficialValveServer() => __pbn__IsOfficialValveServer = null;
    private bool? __pbn__IsOfficialValveServer;

    [global::ProtoBuf.ProtoMember(5, Name = @"is_hltv")]
    public bool IsHltv
    {
        get { return __pbn__IsHltv.GetValueOrDefault(); }
        set { __pbn__IsHltv = value; }
    }
    public bool ShouldSerializeIsHltv() => __pbn__IsHltv != null;
    public void ResetIsHltv() => __pbn__IsHltv = null;
    private bool? __pbn__IsHltv;

    [global::ProtoBuf.ProtoMember(6, Name = @"is_replay")]
    public bool IsReplay
    {
        get { return __pbn__IsReplay.GetValueOrDefault(); }
        set { __pbn__IsReplay = value; }
    }
    public bool ShouldSerializeIsReplay() => __pbn__IsReplay != null;
    public void ResetIsReplay() => __pbn__IsReplay = null;
    private bool? __pbn__IsReplay;

    [global::ProtoBuf.ProtoMember(21, Name = @"is_redirecting_to_proxy_relay")]
    public bool IsRedirectingToProxyRelay
    {
        get { return __pbn__IsRedirectingToProxyRelay.GetValueOrDefault(); }
        set { __pbn__IsRedirectingToProxyRelay = value; }
    }
    public bool ShouldSerializeIsRedirectingToProxyRelay() => __pbn__IsRedirectingToProxyRelay != null;
    public void ResetIsRedirectingToProxyRelay() => __pbn__IsRedirectingToProxyRelay = null;
    private bool? __pbn__IsRedirectingToProxyRelay;

    [global::ProtoBuf.ProtoMember(7, Name = @"c_os")]
    public int COs
    {
        get { return __pbn__COs.GetValueOrDefault(); }
        set { __pbn__COs = value; }
    }
    public bool ShouldSerializeCOs() => __pbn__COs != null;
    public void ResetCOs() => __pbn__COs = null;
    private int? __pbn__COs;

    [global::ProtoBuf.ProtoMember(8, Name = @"map_crc", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint MapCrc
    {
        get { return __pbn__MapCrc.GetValueOrDefault(); }
        set { __pbn__MapCrc = value; }
    }
    public bool ShouldSerializeMapCrc() => __pbn__MapCrc != null;
    public void ResetMapCrc() => __pbn__MapCrc = null;
    private uint? __pbn__MapCrc;

    [global::ProtoBuf.ProtoMember(9, Name = @"client_crc", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint ClientCrc
    {
        get { return __pbn__ClientCrc.GetValueOrDefault(); }
        set { __pbn__ClientCrc = value; }
    }
    public bool ShouldSerializeClientCrc() => __pbn__ClientCrc != null;
    public void ResetClientCrc() => __pbn__ClientCrc = null;
    private uint? __pbn__ClientCrc;

    [global::ProtoBuf.ProtoMember(10, Name = @"string_table_crc", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint StringTableCrc
    {
        get { return __pbn__StringTableCrc.GetValueOrDefault(); }
        set { __pbn__StringTableCrc = value; }
    }
    public bool ShouldSerializeStringTableCrc() => __pbn__StringTableCrc != null;
    public void ResetStringTableCrc() => __pbn__StringTableCrc = null;
    private uint? __pbn__StringTableCrc;

    [global::ProtoBuf.ProtoMember(11, Name = @"max_clients")]
    public int MaxClients
    {
        get { return __pbn__MaxClients.GetValueOrDefault(); }
        set { __pbn__MaxClients = value; }
    }
    public bool ShouldSerializeMaxClients() => __pbn__MaxClients != null;
    public void ResetMaxClients() => __pbn__MaxClients = null;
    private int? __pbn__MaxClients;

    [global::ProtoBuf.ProtoMember(12, Name = @"max_classes")]
    public int MaxClasses
    {
        get { return __pbn__MaxClasses.GetValueOrDefault(); }
        set { __pbn__MaxClasses = value; }
    }
    public bool ShouldSerializeMaxClasses() => __pbn__MaxClasses != null;
    public void ResetMaxClasses() => __pbn__MaxClasses = null;
    private int? __pbn__MaxClasses;

    [global::ProtoBuf.ProtoMember(13, Name = @"player_slot")]
    public int PlayerSlot
    {
        get { return __pbn__PlayerSlot.GetValueOrDefault(); }
        set { __pbn__PlayerSlot = value; }
    }
    public bool ShouldSerializePlayerSlot() => __pbn__PlayerSlot != null;
    public void ResetPlayerSlot() => __pbn__PlayerSlot = null;
    private int? __pbn__PlayerSlot;

    [global::ProtoBuf.ProtoMember(14, Name = @"tick_interval")]
    public float TickInterval
    {
        get { return __pbn__TickInterval.GetValueOrDefault(); }
        set { __pbn__TickInterval = value; }
    }
    public bool ShouldSerializeTickInterval() => __pbn__TickInterval != null;
    public void ResetTickInterval() => __pbn__TickInterval = null;
    private float? __pbn__TickInterval;

    [global::ProtoBuf.ProtoMember(15, Name = @"game_dir")]
    [global::System.ComponentModel.DefaultValue("")]
    public string GameDir
    {
        get { return __pbn__GameDir ?? ""; }
        set { __pbn__GameDir = value; }
    }
    public bool ShouldSerializeGameDir() => __pbn__GameDir != null;
    public void ResetGameDir() => __pbn__GameDir = null;
    private string __pbn__GameDir;

    [global::ProtoBuf.ProtoMember(16, Name = @"map_name")]
    [global::System.ComponentModel.DefaultValue("")]
    public string MapName
    {
        get { return __pbn__MapName ?? ""; }
        set { __pbn__MapName = value; }
    }
    public bool ShouldSerializeMapName() => __pbn__MapName != null;
    public void ResetMapName() => __pbn__MapName = null;
    private string __pbn__MapName;

    [global::ProtoBuf.ProtoMember(17, Name = @"map_group_name")]
    [global::System.ComponentModel.DefaultValue("")]
    public string MapGroupName
    {
        get { return __pbn__MapGroupName ?? ""; }
        set { __pbn__MapGroupName = value; }
    }
    public bool ShouldSerializeMapGroupName() => __pbn__MapGroupName != null;
    public void ResetMapGroupName() => __pbn__MapGroupName = null;
    private string __pbn__MapGroupName;

    [global::ProtoBuf.ProtoMember(18, Name = @"sky_name")]
    [global::System.ComponentModel.DefaultValue("")]
    public string SkyName
    {
        get { return __pbn__SkyName ?? ""; }
        set { __pbn__SkyName = value; }
    }
    public bool ShouldSerializeSkyName() => __pbn__SkyName != null;
    public void ResetSkyName() => __pbn__SkyName = null;
    private string __pbn__SkyName;

    [global::ProtoBuf.ProtoMember(19, Name = @"host_name")]
    [global::System.ComponentModel.DefaultValue("")]
    public string HostName
    {
        get { return __pbn__HostName ?? ""; }
        set { __pbn__HostName = value; }
    }
    public bool ShouldSerializeHostName() => __pbn__HostName != null;
    public void ResetHostName() => __pbn__HostName = null;
    private string __pbn__HostName;

    [global::ProtoBuf.ProtoMember(22, Name = @"ugc_map_id")]
    public ulong UgcMapId
    {
        get { return __pbn__UgcMapId.GetValueOrDefault(); }
        set { __pbn__UgcMapId = value; }
    }
    public bool ShouldSerializeUgcMapId() => __pbn__UgcMapId != null;
    public void ResetUgcMapId() => __pbn__UgcMapId = null;
    private ulong? __pbn__UgcMapId;

}

[global::ProtoBuf.ProtoContract(Name = @"CSVCMsg_ClassInfo")]
public partial class CSVCMsgClassInfo : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"create_on_client")]
    public bool CreateOnClient
    {
        get { return __pbn__CreateOnClient.GetValueOrDefault(); }
        set { __pbn__CreateOnClient = value; }
    }
    public bool ShouldSerializeCreateOnClient() => __pbn__CreateOnClient != null;
    public void ResetCreateOnClient() => __pbn__CreateOnClient = null;
    private bool? __pbn__CreateOnClient;

    [global::ProtoBuf.ProtoMember(2, Name = @"classes")]
    public global::System.Collections.Generic.List<ClassT> Classes { get; } = new global::System.Collections.Generic.List<ClassT>();

    [global::ProtoBuf.ProtoContract(Name = @"class_t")]
    public partial class ClassT : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"class_id")]
        public int ClassId
        {
            get { return __pbn__ClassId.GetValueOrDefault(); }
            set { __pbn__ClassId = value; }
        }
        public bool ShouldSerializeClassId() => __pbn__ClassId != null;
        public void ResetClassId() => __pbn__ClassId = null;
        private int? __pbn__ClassId;

        [global::ProtoBuf.ProtoMember(2, Name = @"data_table_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DataTableName
        {
            get { return __pbn__DataTableName ?? ""; }
            set { __pbn__DataTableName = value; }
        }
        public bool ShouldSerializeDataTableName() => __pbn__DataTableName != null;
        public void ResetDataTableName() => __pbn__DataTableName = null;
        private string __pbn__DataTableName;

        [global::ProtoBuf.ProtoMember(3, Name = @"class_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ClassName
        {
            get { return __pbn__ClassName ?? ""; }
            set { __pbn__ClassName = value; }
        }
        public bool ShouldSerializeClassName() => __pbn__ClassName != null;
        public void ResetClassName() => __pbn__ClassName = null;
        private string __pbn__ClassName;

    }

}

[global::ProtoBuf.ProtoContract(Name = @"CSVCMsg_SendTable")]
public partial class CSVCMsgSendTable : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"is_end")]
    public bool IsEnd
    {
        get { return __pbn__IsEnd.GetValueOrDefault(); }
        set { __pbn__IsEnd = value; }
    }
    public bool ShouldSerializeIsEnd() => __pbn__IsEnd != null;
    public void ResetIsEnd() => __pbn__IsEnd = null;
    private bool? __pbn__IsEnd;

    [global::ProtoBuf.ProtoMember(2, Name = @"net_table_name")]
    [global::System.ComponentModel.DefaultValue("")]
    public string NetTableName
    {
        get { return __pbn__NetTableName ?? ""; }
        set { __pbn__NetTableName = value; }
    }
    public bool ShouldSerializeNetTableName() => __pbn__NetTableName != null;
    public void ResetNetTableName() => __pbn__NetTableName = null;
    private string __pbn__NetTableName;

    [global::ProtoBuf.ProtoMember(3, Name = @"needs_decoder")]
    public bool NeedsDecoder
    {
        get { return __pbn__NeedsDecoder.GetValueOrDefault(); }
        set { __pbn__NeedsDecoder = value; }
    }
    public bool ShouldSerializeNeedsDecoder() => __pbn__NeedsDecoder != null;
    public void ResetNeedsDecoder() => __pbn__NeedsDecoder = null;
    private bool? __pbn__NeedsDecoder;

    [global::ProtoBuf.ProtoMember(4, Name = @"props")]
    public global::System.Collections.Generic.List<SendpropT> Props { get; } = new global::System.Collections.Generic.List<SendpropT>();

    [global::ProtoBuf.ProtoContract(Name = @"sendprop_t")]
    public partial class SendpropT : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public int Type
        {
            get { return __pbn__Type.GetValueOrDefault(); }
            set { __pbn__Type = value; }
        }
        public bool ShouldSerializeType() => __pbn__Type != null;
        public void ResetType() => __pbn__Type = null;
        private int? __pbn__Type;

        [global::ProtoBuf.ProtoMember(2, Name = @"var_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string VarName
        {
            get { return __pbn__VarName ?? ""; }
            set { __pbn__VarName = value; }
        }
        public bool ShouldSerializeVarName() => __pbn__VarName != null;
        public void ResetVarName() => __pbn__VarName = null;
        private string __pbn__VarName;

        [global::ProtoBuf.ProtoMember(3, Name = @"flags")]
        public int Flags
        {
            get { return __pbn__Flags.GetValueOrDefault(); }
            set { __pbn__Flags = value; }
        }
        public bool ShouldSerializeFlags() => __pbn__Flags != null;
        public void ResetFlags() => __pbn__Flags = null;
        private int? __pbn__Flags;

        [global::ProtoBuf.ProtoMember(4, Name = @"priority")]
        public int Priority
        {
            get { return __pbn__Priority.GetValueOrDefault(); }
            set { __pbn__Priority = value; }
        }
        public bool ShouldSerializePriority() => __pbn__Priority != null;
        public void ResetPriority() => __pbn__Priority = null;
        private int? __pbn__Priority;

        [global::ProtoBuf.ProtoMember(5, Name = @"dt_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DtName
        {
            get { return __pbn__DtName ?? ""; }
            set { __pbn__DtName = value; }
        }
        public bool ShouldSerializeDtName() => __pbn__DtName != null;
        public void ResetDtName() => __pbn__DtName = null;
        private string __pbn__DtName;

        [global::ProtoBuf.ProtoMember(6, Name = @"num_elements")]
        public int NumElements
        {
            get { return __pbn__NumElements.GetValueOrDefault(); }
            set { __pbn__NumElements = value; }
        }
        public bool ShouldSerializeNumElements() => __pbn__NumElements != null;
        public void ResetNumElements() => __pbn__NumElements = null;
        private int? __pbn__NumElements;

        [global::ProtoBuf.ProtoMember(7, Name = @"low_value")]
        public float LowValue
        {
            get { return __pbn__LowValue.GetValueOrDefault(); }
            set { __pbn__LowValue = value; }
        }
        public bool ShouldSerializeLowValue() => __pbn__LowValue != null;
        public void ResetLowValue() => __pbn__LowValue = null;
        private float? __pbn__LowValue;

        [global::ProtoBuf.ProtoMember(8, Name = @"high_value")]
        public float HighValue
        {
            get { return __pbn__HighValue.GetValueOrDefault(); }
            set { __pbn__HighValue = value; }
        }
        public bool ShouldSerializeHighValue() => __pbn__HighValue != null;
        public void ResetHighValue() => __pbn__HighValue = null;
        private float? __pbn__HighValue;

        [global::ProtoBuf.ProtoMember(9, Name = @"num_bits")]
        public int NumBits
        {
            get { return __pbn__NumBits.GetValueOrDefault(); }
            set { __pbn__NumBits = value; }
        }
        public bool ShouldSerializeNumBits() => __pbn__NumBits != null;
        public void ResetNumBits() => __pbn__NumBits = null;
        private int? __pbn__NumBits;

    }

}

[global::ProtoBuf.ProtoContract(Name = @"CSVCMsg_Print")]
public partial class CSVCMsgPrint : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"text")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Text
    {
        get { return __pbn__Text ?? ""; }
        set { __pbn__Text = value; }
    }
    public bool ShouldSerializeText() => __pbn__Text != null;
    public void ResetText() => __pbn__Text = null;
    private string __pbn__Text;

}

[global::ProtoBuf.ProtoContract(Name = @"CSVCMsg_SetPause")]
public partial class CSVCMsgSetPause : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"paused")]
    public bool Paused
    {
        get { return __pbn__Paused.GetValueOrDefault(); }
        set { __pbn__Paused = value; }
    }
    public bool ShouldSerializePaused() => __pbn__Paused != null;
    public void ResetPaused() => __pbn__Paused = null;
    private bool? __pbn__Paused;

}

[global::ProtoBuf.ProtoContract(Name = @"CSVCMsg_SetView")]
public partial class CSVCMsgSetView : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"entity_index")]
    public int EntityIndex
    {
        get { return __pbn__EntityIndex.GetValueOrDefault(); }
        set { __pbn__EntityIndex = value; }
    }
    public bool ShouldSerializeEntityIndex() => __pbn__EntityIndex != null;
    public void ResetEntityIndex() => __pbn__EntityIndex = null;
    private int? __pbn__EntityIndex;

}

[global::ProtoBuf.ProtoContract(Name = @"CSVCMsg_CreateStringTable")]
public partial class CSVCMsgCreateStringTable : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"name")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Name
    {
        get { return __pbn__Name ?? ""; }
        set { __pbn__Name = value; }
    }
    public bool ShouldSerializeName() => __pbn__Name != null;
    public void ResetName() => __pbn__Name = null;
    private string __pbn__Name;

    [global::ProtoBuf.ProtoMember(2, Name = @"max_entries")]
    public int MaxEntries
    {
        get { return __pbn__MaxEntries.GetValueOrDefault(); }
        set { __pbn__MaxEntries = value; }
    }
    public bool ShouldSerializeMaxEntries() => __pbn__MaxEntries != null;
    public void ResetMaxEntries() => __pbn__MaxEntries = null;
    private int? __pbn__MaxEntries;

    [global::ProtoBuf.ProtoMember(3, Name = @"num_entries")]
    public int NumEntries
    {
        get { return __pbn__NumEntries.GetValueOrDefault(); }
        set { __pbn__NumEntries = value; }
    }
    public bool ShouldSerializeNumEntries() => __pbn__NumEntries != null;
    public void ResetNumEntries() => __pbn__NumEntries = null;
    private int? __pbn__NumEntries;

    [global::ProtoBuf.ProtoMember(4, Name = @"user_data_fixed_size")]
    public bool UserDataFixedSize
    {
        get { return __pbn__UserDataFixedSize.GetValueOrDefault(); }
        set { __pbn__UserDataFixedSize = value; }
    }
    public bool ShouldSerializeUserDataFixedSize() => __pbn__UserDataFixedSize != null;
    public void ResetUserDataFixedSize() => __pbn__UserDataFixedSize = null;
    private bool? __pbn__UserDataFixedSize;

    [global::ProtoBuf.ProtoMember(5, Name = @"user_data_size")]
    public int UserDataSize
    {
        get { return __pbn__UserDataSize.GetValueOrDefault(); }
        set { __pbn__UserDataSize = value; }
    }
    public bool ShouldSerializeUserDataSize() => __pbn__UserDataSize != null;
    public void ResetUserDataSize() => __pbn__UserDataSize = null;
    private int? __pbn__UserDataSize;

    [global::ProtoBuf.ProtoMember(6, Name = @"user_data_size_bits")]
    public int UserDataSizeBits
    {
        get { return __pbn__UserDataSizeBits.GetValueOrDefault(); }
        set { __pbn__UserDataSizeBits = value; }
    }
    public bool ShouldSerializeUserDataSizeBits() => __pbn__UserDataSizeBits != null;
    public void ResetUserDataSizeBits() => __pbn__UserDataSizeBits = null;
    private int? __pbn__UserDataSizeBits;

    [global::ProtoBuf.ProtoMember(7, Name = @"flags")]
    public int Flags
    {
        get { return __pbn__Flags.GetValueOrDefault(); }
        set { __pbn__Flags = value; }
    }
    public bool ShouldSerializeFlags() => __pbn__Flags != null;
    public void ResetFlags() => __pbn__Flags = null;
    private int? __pbn__Flags;

    [global::ProtoBuf.ProtoMember(8, Name = @"string_data")]
    public byte[] StringData
    {
        get { return __pbn__StringData; }
        set { __pbn__StringData = value; }
    }
    public bool ShouldSerializeStringData() => __pbn__StringData != null;
    public void ResetStringData() => __pbn__StringData = null;
    private byte[] __pbn__StringData;

}

[global::ProtoBuf.ProtoContract(Name = @"CSVCMsg_UpdateStringTable")]
public partial class CSVCMsgUpdateStringTable : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"table_id")]
    public int TableId
    {
        get { return __pbn__TableId.GetValueOrDefault(); }
        set { __pbn__TableId = value; }
    }
    public bool ShouldSerializeTableId() => __pbn__TableId != null;
    public void ResetTableId() => __pbn__TableId = null;
    private int? __pbn__TableId;

    [global::ProtoBuf.ProtoMember(2, Name = @"num_changed_entries")]
    public int NumChangedEntries
    {
        get { return __pbn__NumChangedEntries.GetValueOrDefault(); }
        set { __pbn__NumChangedEntries = value; }
    }
    public bool ShouldSerializeNumChangedEntries() => __pbn__NumChangedEntries != null;
    public void ResetNumChangedEntries() => __pbn__NumChangedEntries = null;
    private int? __pbn__NumChangedEntries;

    [global::ProtoBuf.ProtoMember(3, Name = @"string_data")]
    public byte[] StringData
    {
        get { return __pbn__StringData; }
        set { __pbn__StringData = value; }
    }
    public bool ShouldSerializeStringData() => __pbn__StringData != null;
    public void ResetStringData() => __pbn__StringData = null;
    private byte[] __pbn__StringData;

}

[global::ProtoBuf.ProtoContract(Name = @"CSVCMsg_VoiceInit")]
public partial class CSVCMsgVoiceInit : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"quality")]
    public int Quality
    {
        get { return __pbn__Quality.GetValueOrDefault(); }
        set { __pbn__Quality = value; }
    }
    public bool ShouldSerializeQuality() => __pbn__Quality != null;
    public void ResetQuality() => __pbn__Quality = null;
    private int? __pbn__Quality;

    [global::ProtoBuf.ProtoMember(2, Name = @"codec")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Codec
    {
        get { return __pbn__Codec ?? ""; }
        set { __pbn__Codec = value; }
    }
    public bool ShouldSerializeCodec() => __pbn__Codec != null;
    public void ResetCodec() => __pbn__Codec = null;
    private string __pbn__Codec;

}

[global::ProtoBuf.ProtoContract(Name = @"CSVCMsg_VoiceData")]
public partial class CSVCMsgVoiceData : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"client")]
    public int Client
    {
        get { return __pbn__Client.GetValueOrDefault(); }
        set { __pbn__Client = value; }
    }
    public bool ShouldSerializeClient() => __pbn__Client != null;
    public void ResetClient() => __pbn__Client = null;
    private int? __pbn__Client;

    [global::ProtoBuf.ProtoMember(2, Name = @"proximity")]
    public bool Proximity
    {
        get { return __pbn__Proximity.GetValueOrDefault(); }
        set { __pbn__Proximity = value; }
    }
    public bool ShouldSerializeProximity() => __pbn__Proximity != null;
    public void ResetProximity() => __pbn__Proximity = null;
    private bool? __pbn__Proximity;

    [global::ProtoBuf.ProtoMember(3, Name = @"xuid", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public ulong Xuid
    {
        get { return __pbn__Xuid.GetValueOrDefault(); }
        set { __pbn__Xuid = value; }
    }
    public bool ShouldSerializeXuid() => __pbn__Xuid != null;
    public void ResetXuid() => __pbn__Xuid = null;
    private ulong? __pbn__Xuid;

    [global::ProtoBuf.ProtoMember(4, Name = @"audible_mask")]
    public int AudibleMask
    {
        get { return __pbn__AudibleMask.GetValueOrDefault(); }
        set { __pbn__AudibleMask = value; }
    }
    public bool ShouldSerializeAudibleMask() => __pbn__AudibleMask != null;
    public void ResetAudibleMask() => __pbn__AudibleMask = null;
    private int? __pbn__AudibleMask;

    [global::ProtoBuf.ProtoMember(5, Name = @"voice_data")]
    public byte[] VoiceData
    {
        get { return __pbn__VoiceData; }
        set { __pbn__VoiceData = value; }
    }
    public bool ShouldSerializeVoiceData() => __pbn__VoiceData != null;
    public void ResetVoiceData() => __pbn__VoiceData = null;
    private byte[] __pbn__VoiceData;

}

[global::ProtoBuf.ProtoContract(Name = @"CSVCMsg_FixAngle")]
public partial class CSVCMsgFixAngle : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"relative")]
    public bool Relative
    {
        get { return __pbn__Relative.GetValueOrDefault(); }
        set { __pbn__Relative = value; }
    }
    public bool ShouldSerializeRelative() => __pbn__Relative != null;
    public void ResetRelative() => __pbn__Relative = null;
    private bool? __pbn__Relative;

    [global::ProtoBuf.ProtoMember(2, Name = @"angle")]
    public CMsgQAngle Angle { get; set; }

}

[global::ProtoBuf.ProtoContract(Name = @"CSVCMsg_CrosshairAngle")]
public partial class CSVCMsgCrosshairAngle : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"angle")]
    public CMsgQAngle Angle { get; set; }

}

[global::ProtoBuf.ProtoContract(Name = @"CSVCMsg_Prefetch")]
public partial class CSVCMsgPrefetch : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"sound_index")]
    public int SoundIndex
    {
        get { return __pbn__SoundIndex.GetValueOrDefault(); }
        set { __pbn__SoundIndex = value; }
    }
    public bool ShouldSerializeSoundIndex() => __pbn__SoundIndex != null;
    public void ResetSoundIndex() => __pbn__SoundIndex = null;
    private int? __pbn__SoundIndex;

}

[global::ProtoBuf.ProtoContract(Name = @"CSVCMsg_BSPDecal")]
public partial class CSVCMsgBSPDecal : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"pos")]
    public CMsgVector Pos { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"decal_texture_index")]
    public int DecalTextureIndex
    {
        get { return __pbn__DecalTextureIndex.GetValueOrDefault(); }
        set { __pbn__DecalTextureIndex = value; }
    }
    public bool ShouldSerializeDecalTextureIndex() => __pbn__DecalTextureIndex != null;
    public void ResetDecalTextureIndex() => __pbn__DecalTextureIndex = null;
    private int? __pbn__DecalTextureIndex;

    [global::ProtoBuf.ProtoMember(3, Name = @"entity_index")]
    public int EntityIndex
    {
        get { return __pbn__EntityIndex.GetValueOrDefault(); }
        set { __pbn__EntityIndex = value; }
    }
    public bool ShouldSerializeEntityIndex() => __pbn__EntityIndex != null;
    public void ResetEntityIndex() => __pbn__EntityIndex = null;
    private int? __pbn__EntityIndex;

    [global::ProtoBuf.ProtoMember(4, Name = @"model_index")]
    public int ModelIndex
    {
        get { return __pbn__ModelIndex.GetValueOrDefault(); }
        set { __pbn__ModelIndex = value; }
    }
    public bool ShouldSerializeModelIndex() => __pbn__ModelIndex != null;
    public void ResetModelIndex() => __pbn__ModelIndex = null;
    private int? __pbn__ModelIndex;

    [global::ProtoBuf.ProtoMember(5, Name = @"low_priority")]
    public bool LowPriority
    {
        get { return __pbn__LowPriority.GetValueOrDefault(); }
        set { __pbn__LowPriority = value; }
    }
    public bool ShouldSerializeLowPriority() => __pbn__LowPriority != null;
    public void ResetLowPriority() => __pbn__LowPriority = null;
    private bool? __pbn__LowPriority;

}

[global::ProtoBuf.ProtoContract(Name = @"CSVCMsg_GetCvarValue")]
public partial class CSVCMsgGetCvarValue : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"cookie")]
    public int Cookie
    {
        get { return __pbn__Cookie.GetValueOrDefault(); }
        set { __pbn__Cookie = value; }
    }
    public bool ShouldSerializeCookie() => __pbn__Cookie != null;
    public void ResetCookie() => __pbn__Cookie = null;
    private int? __pbn__Cookie;

    [global::ProtoBuf.ProtoMember(2, Name = @"cvar_name")]
    [global::System.ComponentModel.DefaultValue("")]
    public string CvarName
    {
        get { return __pbn__CvarName ?? ""; }
        set { __pbn__CvarName = value; }
    }
    public bool ShouldSerializeCvarName() => __pbn__CvarName != null;
    public void ResetCvarName() => __pbn__CvarName = null;
    private string __pbn__CvarName;

}

[global::ProtoBuf.ProtoContract(Name = @"CSVCMsg_Menu")]
public partial class CSVCMsgMenu : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"dialog_type")]
    public int DialogType
    {
        get { return __pbn__DialogType.GetValueOrDefault(); }
        set { __pbn__DialogType = value; }
    }
    public bool ShouldSerializeDialogType() => __pbn__DialogType != null;
    public void ResetDialogType() => __pbn__DialogType = null;
    private int? __pbn__DialogType;

    [global::ProtoBuf.ProtoMember(2, Name = @"menu_key_values")]
    public byte[] MenuKeyValues
    {
        get { return __pbn__MenuKeyValues; }
        set { __pbn__MenuKeyValues = value; }
    }
    public bool ShouldSerializeMenuKeyValues() => __pbn__MenuKeyValues != null;
    public void ResetMenuKeyValues() => __pbn__MenuKeyValues = null;
    private byte[] __pbn__MenuKeyValues;

}

[global::ProtoBuf.ProtoContract(Name = @"CSVCMsg_UserMessage")]
public partial class CSVCMsgUserMessage : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"msg_type")]
    public int MsgType
    {
        get { return __pbn__MsgType.GetValueOrDefault(); }
        set { __pbn__MsgType = value; }
    }
    public bool ShouldSerializeMsgType() => __pbn__MsgType != null;
    public void ResetMsgType() => __pbn__MsgType = null;
    private int? __pbn__MsgType;

    [global::ProtoBuf.ProtoMember(2, Name = @"msg_data")]
    public byte[] MsgData
    {
        get { return __pbn__MsgData; }
        set { __pbn__MsgData = value; }
    }
    public bool ShouldSerializeMsgData() => __pbn__MsgData != null;
    public void ResetMsgData() => __pbn__MsgData = null;
    private byte[] __pbn__MsgData;

}

[global::ProtoBuf.ProtoContract(Name = @"CSVCMsg_GameEvent")]
public partial class CSVCMsgGameEvent : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"event_name")]
    [global::System.ComponentModel.DefaultValue("")]
    public string EventName
    {
        get { return __pbn__EventName ?? ""; }
        set { __pbn__EventName = value; }
    }
    public bool ShouldSerializeEventName() => __pbn__EventName != null;
    public void ResetEventName() => __pbn__EventName = null;
    private string __pbn__EventName;

    [global::ProtoBuf.ProtoMember(2, Name = @"eventid")]
    public int Eventid
    {
        get { return __pbn__Eventid.GetValueOrDefault(); }
        set { __pbn__Eventid = value; }
    }
    public bool ShouldSerializeEventid() => __pbn__Eventid != null;
    public void ResetEventid() => __pbn__Eventid = null;
    private int? __pbn__Eventid;

    [global::ProtoBuf.ProtoMember(3, Name = @"keys")]
    public global::System.Collections.Generic.List<KeyT> Keys { get; } = new global::System.Collections.Generic.List<KeyT>();

    [global::ProtoBuf.ProtoContract(Name = @"key_t")]
    public partial class KeyT : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public int Type
        {
            get { return __pbn__Type.GetValueOrDefault(); }
            set { __pbn__Type = value; }
        }
        public bool ShouldSerializeType() => __pbn__Type != null;
        public void ResetType() => __pbn__Type = null;
        private int? __pbn__Type;

        [global::ProtoBuf.ProtoMember(2, Name = @"val_string")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ValString
        {
            get { return __pbn__ValString ?? ""; }
            set { __pbn__ValString = value; }
        }
        public bool ShouldSerializeValString() => __pbn__ValString != null;
        public void ResetValString() => __pbn__ValString = null;
        private string __pbn__ValString;

        [global::ProtoBuf.ProtoMember(3, Name = @"val_float")]
        public float ValFloat
        {
            get { return __pbn__ValFloat.GetValueOrDefault(); }
            set { __pbn__ValFloat = value; }
        }
        public bool ShouldSerializeValFloat() => __pbn__ValFloat != null;
        public void ResetValFloat() => __pbn__ValFloat = null;
        private float? __pbn__ValFloat;

        [global::ProtoBuf.ProtoMember(4, Name = @"val_long")]
        public int ValLong
        {
            get { return __pbn__ValLong.GetValueOrDefault(); }
            set { __pbn__ValLong = value; }
        }
        public bool ShouldSerializeValLong() => __pbn__ValLong != null;
        public void ResetValLong() => __pbn__ValLong = null;
        private int? __pbn__ValLong;

        [global::ProtoBuf.ProtoMember(5, Name = @"val_short")]
        public int ValShort
        {
            get { return __pbn__ValShort.GetValueOrDefault(); }
            set { __pbn__ValShort = value; }
        }
        public bool ShouldSerializeValShort() => __pbn__ValShort != null;
        public void ResetValShort() => __pbn__ValShort = null;
        private int? __pbn__ValShort;

        [global::ProtoBuf.ProtoMember(6, Name = @"val_byte")]
        public int ValByte
        {
            get { return __pbn__ValByte.GetValueOrDefault(); }
            set { __pbn__ValByte = value; }
        }
        public bool ShouldSerializeValByte() => __pbn__ValByte != null;
        public void ResetValByte() => __pbn__ValByte = null;
        private int? __pbn__ValByte;

        [global::ProtoBuf.ProtoMember(7, Name = @"val_bool")]
        public bool ValBool
        {
            get { return __pbn__ValBool.GetValueOrDefault(); }
            set { __pbn__ValBool = value; }
        }
        public bool ShouldSerializeValBool() => __pbn__ValBool != null;
        public void ResetValBool() => __pbn__ValBool = null;
        private bool? __pbn__ValBool;

        [global::ProtoBuf.ProtoMember(8, Name = @"val_uint64")]
        public ulong ValUint64
        {
            get { return __pbn__ValUint64.GetValueOrDefault(); }
            set { __pbn__ValUint64 = value; }
        }
        public bool ShouldSerializeValUint64() => __pbn__ValUint64 != null;
        public void ResetValUint64() => __pbn__ValUint64 = null;
        private ulong? __pbn__ValUint64;

        [global::ProtoBuf.ProtoMember(9, Name = @"val_wstring")]
        public byte[] ValWstring
        {
            get { return __pbn__ValWstring; }
            set { __pbn__ValWstring = value; }
        }
        public bool ShouldSerializeValWstring() => __pbn__ValWstring != null;
        public void ResetValWstring() => __pbn__ValWstring = null;
        private byte[] __pbn__ValWstring;

    }

}

[global::ProtoBuf.ProtoContract(Name = @"CSVCMsg_GameEventList")]
public partial class CSVCMsgGameEventList : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"descriptors")]
    public global::System.Collections.Generic.List<DescriptorT> Descriptors { get; } = new global::System.Collections.Generic.List<DescriptorT>();

    [global::ProtoBuf.ProtoContract(Name = @"key_t")]
    public partial class KeyT : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public int Type
        {
            get { return __pbn__Type.GetValueOrDefault(); }
            set { __pbn__Type = value; }
        }
        public bool ShouldSerializeType() => __pbn__Type != null;
        public void ResetType() => __pbn__Type = null;
        private int? __pbn__Type;

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get { return __pbn__Name ?? ""; }
            set { __pbn__Name = value; }
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

    }

    [global::ProtoBuf.ProtoContract(Name = @"descriptor_t")]
    public partial class DescriptorT : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"eventid")]
        public int Eventid
        {
            get { return __pbn__Eventid.GetValueOrDefault(); }
            set { __pbn__Eventid = value; }
        }
        public bool ShouldSerializeEventid() => __pbn__Eventid != null;
        public void ResetEventid() => __pbn__Eventid = null;
        private int? __pbn__Eventid;

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get { return __pbn__Name ?? ""; }
            set { __pbn__Name = value; }
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(3, Name = @"keys")]
        public global::System.Collections.Generic.List<CSVCMsgGameEventList.KeyT> Keys { get; } = new global::System.Collections.Generic.List<CSVCMsgGameEventList.KeyT>();

    }

}

[global::ProtoBuf.ProtoContract(Name = @"CSVCMsg_TempEntities")]
public partial class CSVCMsgTempEntities : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"reliable")]
    public bool Reliable
    {
        get { return __pbn__Reliable.GetValueOrDefault(); }
        set { __pbn__Reliable = value; }
    }
    public bool ShouldSerializeReliable() => __pbn__Reliable != null;
    public void ResetReliable() => __pbn__Reliable = null;
    private bool? __pbn__Reliable;

    [global::ProtoBuf.ProtoMember(2, Name = @"num_entries")]
    public int NumEntries
    {
        get { return __pbn__NumEntries.GetValueOrDefault(); }
        set { __pbn__NumEntries = value; }
    }
    public bool ShouldSerializeNumEntries() => __pbn__NumEntries != null;
    public void ResetNumEntries() => __pbn__NumEntries = null;
    private int? __pbn__NumEntries;

    [global::ProtoBuf.ProtoMember(3, Name = @"entity_data")]
    public byte[] EntityData
    {
        get { return __pbn__EntityData; }
        set { __pbn__EntityData = value; }
    }
    public bool ShouldSerializeEntityData() => __pbn__EntityData != null;
    public void ResetEntityData() => __pbn__EntityData = null;
    private byte[] __pbn__EntityData;

}

[global::ProtoBuf.ProtoContract(Name = @"CSVCMsg_PacketEntities")]
public partial class CSVCMsgPacketEntities : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"max_entries")]
    public int MaxEntries
    {
        get { return __pbn__MaxEntries.GetValueOrDefault(); }
        set { __pbn__MaxEntries = value; }
    }
    public bool ShouldSerializeMaxEntries() => __pbn__MaxEntries != null;
    public void ResetMaxEntries() => __pbn__MaxEntries = null;
    private int? __pbn__MaxEntries;

    [global::ProtoBuf.ProtoMember(2, Name = @"updated_entries")]
    public int UpdatedEntries
    {
        get { return __pbn__UpdatedEntries.GetValueOrDefault(); }
        set { __pbn__UpdatedEntries = value; }
    }
    public bool ShouldSerializeUpdatedEntries() => __pbn__UpdatedEntries != null;
    public void ResetUpdatedEntries() => __pbn__UpdatedEntries = null;
    private int? __pbn__UpdatedEntries;

    [global::ProtoBuf.ProtoMember(3, Name = @"is_delta")]
    public bool IsDelta
    {
        get { return __pbn__IsDelta.GetValueOrDefault(); }
        set { __pbn__IsDelta = value; }
    }
    public bool ShouldSerializeIsDelta() => __pbn__IsDelta != null;
    public void ResetIsDelta() => __pbn__IsDelta = null;
    private bool? __pbn__IsDelta;

    [global::ProtoBuf.ProtoMember(4, Name = @"update_baseline")]
    public bool UpdateBaseline
    {
        get { return __pbn__UpdateBaseline.GetValueOrDefault(); }
        set { __pbn__UpdateBaseline = value; }
    }
    public bool ShouldSerializeUpdateBaseline() => __pbn__UpdateBaseline != null;
    public void ResetUpdateBaseline() => __pbn__UpdateBaseline = null;
    private bool? __pbn__UpdateBaseline;

    [global::ProtoBuf.ProtoMember(5, Name = @"baseline")]
    public int Baseline
    {
        get { return __pbn__Baseline.GetValueOrDefault(); }
        set { __pbn__Baseline = value; }
    }
    public bool ShouldSerializeBaseline() => __pbn__Baseline != null;
    public void ResetBaseline() => __pbn__Baseline = null;
    private int? __pbn__Baseline;

    [global::ProtoBuf.ProtoMember(6, Name = @"delta_from")]
    public int DeltaFrom
    {
        get { return __pbn__DeltaFrom.GetValueOrDefault(); }
        set { __pbn__DeltaFrom = value; }
    }
    public bool ShouldSerializeDeltaFrom() => __pbn__DeltaFrom != null;
    public void ResetDeltaFrom() => __pbn__DeltaFrom = null;
    private int? __pbn__DeltaFrom;

    [global::ProtoBuf.ProtoMember(7, Name = @"entity_data")]
    public byte[] EntityData
    {
        get { return __pbn__EntityData; }
        set { __pbn__EntityData = value; }
    }
    public bool ShouldSerializeEntityData() => __pbn__EntityData != null;
    public void ResetEntityData() => __pbn__EntityData = null;
    private byte[] __pbn__EntityData;

}

[global::ProtoBuf.ProtoContract(Name = @"CSVCMsg_Sounds")]
public partial class CSVCMsgSounds : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"reliable_sound")]
    public bool ReliableSound
    {
        get { return __pbn__ReliableSound.GetValueOrDefault(); }
        set { __pbn__ReliableSound = value; }
    }
    public bool ShouldSerializeReliableSound() => __pbn__ReliableSound != null;
    public void ResetReliableSound() => __pbn__ReliableSound = null;
    private bool? __pbn__ReliableSound;

    [global::ProtoBuf.ProtoMember(2, Name = @"sounds")]
    public global::System.Collections.Generic.List<SounddataT> Sounds { get; } = new global::System.Collections.Generic.List<SounddataT>();

    [global::ProtoBuf.ProtoContract(Name = @"sounddata_t")]
    public partial class SounddataT : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"origin_x", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int OriginX
        {
            get { return __pbn__OriginX.GetValueOrDefault(); }
            set { __pbn__OriginX = value; }
        }
        public bool ShouldSerializeOriginX() => __pbn__OriginX != null;
        public void ResetOriginX() => __pbn__OriginX = null;
        private int? __pbn__OriginX;

        [global::ProtoBuf.ProtoMember(2, Name = @"origin_y", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int OriginY
        {
            get { return __pbn__OriginY.GetValueOrDefault(); }
            set { __pbn__OriginY = value; }
        }
        public bool ShouldSerializeOriginY() => __pbn__OriginY != null;
        public void ResetOriginY() => __pbn__OriginY = null;
        private int? __pbn__OriginY;

        [global::ProtoBuf.ProtoMember(3, Name = @"origin_z", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int OriginZ
        {
            get { return __pbn__OriginZ.GetValueOrDefault(); }
            set { __pbn__OriginZ = value; }
        }
        public bool ShouldSerializeOriginZ() => __pbn__OriginZ != null;
        public void ResetOriginZ() => __pbn__OriginZ = null;
        private int? __pbn__OriginZ;

        [global::ProtoBuf.ProtoMember(4, Name = @"volume")]
        public uint Volume
        {
            get { return __pbn__Volume.GetValueOrDefault(); }
            set { __pbn__Volume = value; }
        }
        public bool ShouldSerializeVolume() => __pbn__Volume != null;
        public void ResetVolume() => __pbn__Volume = null;
        private uint? __pbn__Volume;

        [global::ProtoBuf.ProtoMember(5, Name = @"delay_value")]
        public float DelayValue
        {
            get { return __pbn__DelayValue.GetValueOrDefault(); }
            set { __pbn__DelayValue = value; }
        }
        public bool ShouldSerializeDelayValue() => __pbn__DelayValue != null;
        public void ResetDelayValue() => __pbn__DelayValue = null;
        private float? __pbn__DelayValue;

        [global::ProtoBuf.ProtoMember(6, Name = @"sequence_number")]
        public int SequenceNumber
        {
            get { return __pbn__SequenceNumber.GetValueOrDefault(); }
            set { __pbn__SequenceNumber = value; }
        }
        public bool ShouldSerializeSequenceNumber() => __pbn__SequenceNumber != null;
        public void ResetSequenceNumber() => __pbn__SequenceNumber = null;
        private int? __pbn__SequenceNumber;

        [global::ProtoBuf.ProtoMember(7, Name = @"entity_index")]
        public int EntityIndex
        {
            get { return __pbn__EntityIndex.GetValueOrDefault(); }
            set { __pbn__EntityIndex = value; }
        }
        public bool ShouldSerializeEntityIndex() => __pbn__EntityIndex != null;
        public void ResetEntityIndex() => __pbn__EntityIndex = null;
        private int? __pbn__EntityIndex;

        [global::ProtoBuf.ProtoMember(8, Name = @"channel")]
        public int Channel
        {
            get { return __pbn__Channel.GetValueOrDefault(); }
            set { __pbn__Channel = value; }
        }
        public bool ShouldSerializeChannel() => __pbn__Channel != null;
        public void ResetChannel() => __pbn__Channel = null;
        private int? __pbn__Channel;

        [global::ProtoBuf.ProtoMember(9, Name = @"pitch")]
        public int Pitch
        {
            get { return __pbn__Pitch.GetValueOrDefault(); }
            set { __pbn__Pitch = value; }
        }
        public bool ShouldSerializePitch() => __pbn__Pitch != null;
        public void ResetPitch() => __pbn__Pitch = null;
        private int? __pbn__Pitch;

        [global::ProtoBuf.ProtoMember(10, Name = @"flags")]
        public int Flags
        {
            get { return __pbn__Flags.GetValueOrDefault(); }
            set { __pbn__Flags = value; }
        }
        public bool ShouldSerializeFlags() => __pbn__Flags != null;
        public void ResetFlags() => __pbn__Flags = null;
        private int? __pbn__Flags;

        [global::ProtoBuf.ProtoMember(11, Name = @"sound_num")]
        public uint SoundNum
        {
            get { return __pbn__SoundNum.GetValueOrDefault(); }
            set { __pbn__SoundNum = value; }
        }
        public bool ShouldSerializeSoundNum() => __pbn__SoundNum != null;
        public void ResetSoundNum() => __pbn__SoundNum = null;
        private uint? __pbn__SoundNum;

        [global::ProtoBuf.ProtoMember(12, Name = @"sound_num_handle", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public uint SoundNumHandle
        {
            get { return __pbn__SoundNumHandle.GetValueOrDefault(); }
            set { __pbn__SoundNumHandle = value; }
        }
        public bool ShouldSerializeSoundNumHandle() => __pbn__SoundNumHandle != null;
        public void ResetSoundNumHandle() => __pbn__SoundNumHandle = null;
        private uint? __pbn__SoundNumHandle;

        [global::ProtoBuf.ProtoMember(13, Name = @"speaker_entity")]
        public int SpeakerEntity
        {
            get { return __pbn__SpeakerEntity.GetValueOrDefault(); }
            set { __pbn__SpeakerEntity = value; }
        }
        public bool ShouldSerializeSpeakerEntity() => __pbn__SpeakerEntity != null;
        public void ResetSpeakerEntity() => __pbn__SpeakerEntity = null;
        private int? __pbn__SpeakerEntity;

        [global::ProtoBuf.ProtoMember(14, Name = @"random_seed")]
        public int RandomSeed
        {
            get { return __pbn__RandomSeed.GetValueOrDefault(); }
            set { __pbn__RandomSeed = value; }
        }
        public bool ShouldSerializeRandomSeed() => __pbn__RandomSeed != null;
        public void ResetRandomSeed() => __pbn__RandomSeed = null;
        private int? __pbn__RandomSeed;

        [global::ProtoBuf.ProtoMember(15, Name = @"sound_level")]
        public int SoundLevel
        {
            get { return __pbn__SoundLevel.GetValueOrDefault(); }
            set { __pbn__SoundLevel = value; }
        }
        public bool ShouldSerializeSoundLevel() => __pbn__SoundLevel != null;
        public void ResetSoundLevel() => __pbn__SoundLevel = null;
        private int? __pbn__SoundLevel;

        [global::ProtoBuf.ProtoMember(16, Name = @"is_sentence")]
        public bool IsSentence
        {
            get { return __pbn__IsSentence.GetValueOrDefault(); }
            set { __pbn__IsSentence = value; }
        }
        public bool ShouldSerializeIsSentence() => __pbn__IsSentence != null;
        public void ResetIsSentence() => __pbn__IsSentence = null;
        private bool? __pbn__IsSentence;

        [global::ProtoBuf.ProtoMember(17, Name = @"is_ambient")]
        public bool IsAmbient
        {
            get { return __pbn__IsAmbient.GetValueOrDefault(); }
            set { __pbn__IsAmbient = value; }
        }
        public bool ShouldSerializeIsAmbient() => __pbn__IsAmbient != null;
        public void ResetIsAmbient() => __pbn__IsAmbient = null;
        private bool? __pbn__IsAmbient;

    }

}

[global::ProtoBuf.ProtoContract(Name = @"NET_Messages")]
public enum NETMessages
{
    [global::ProtoBuf.ProtoEnum(Name = @"net_NOP")]
    netNOP = 0,
    [global::ProtoBuf.ProtoEnum(Name = @"net_Disconnect")]
    netDisconnect = 1,
    [global::ProtoBuf.ProtoEnum(Name = @"net_File")]
    netFile = 2,
    [global::ProtoBuf.ProtoEnum(Name = @"net_Tick")]
    netTick = 4,
    [global::ProtoBuf.ProtoEnum(Name = @"net_StringCmd")]
    netStringCmd = 5,
    [global::ProtoBuf.ProtoEnum(Name = @"net_SetConVar")]
    netSetConVar = 6,
    [global::ProtoBuf.ProtoEnum(Name = @"net_SignonState")]
    netSignonState = 7,
}

[global::ProtoBuf.ProtoContract(Name = @"SVC_Messages")]
public enum SVCMessages
{
    [global::ProtoBuf.ProtoEnum(Name = @"svc_ServerInfo")]
    svcServerInfo = 8,
    [global::ProtoBuf.ProtoEnum(Name = @"svc_SendTable")]
    svcSendTable = 9,
    [global::ProtoBuf.ProtoEnum(Name = @"svc_ClassInfo")]
    svcClassInfo = 10,
    [global::ProtoBuf.ProtoEnum(Name = @"svc_SetPause")]
    svcSetPause = 11,
    [global::ProtoBuf.ProtoEnum(Name = @"svc_CreateStringTable")]
    svcCreateStringTable = 12,
    [global::ProtoBuf.ProtoEnum(Name = @"svc_UpdateStringTable")]
    svcUpdateStringTable = 13,
    [global::ProtoBuf.ProtoEnum(Name = @"svc_VoiceInit")]
    svcVoiceInit = 14,
    [global::ProtoBuf.ProtoEnum(Name = @"svc_VoiceData")]
    svcVoiceData = 15,
    [global::ProtoBuf.ProtoEnum(Name = @"svc_Print")]
    svcPrint = 16,
    [global::ProtoBuf.ProtoEnum(Name = @"svc_Sounds")]
    svcSounds = 17,
    [global::ProtoBuf.ProtoEnum(Name = @"svc_SetView")]
    svcSetView = 18,
    [global::ProtoBuf.ProtoEnum(Name = @"svc_FixAngle")]
    svcFixAngle = 19,
    [global::ProtoBuf.ProtoEnum(Name = @"svc_CrosshairAngle")]
    svcCrosshairAngle = 20,
    [global::ProtoBuf.ProtoEnum(Name = @"svc_BSPDecal")]
    svcBSPDecal = 21,
    [global::ProtoBuf.ProtoEnum(Name = @"svc_UserMessage")]
    svcUserMessage = 23,
    [global::ProtoBuf.ProtoEnum(Name = @"svc_GameEvent")]
    svcGameEvent = 25,
    [global::ProtoBuf.ProtoEnum(Name = @"svc_PacketEntities")]
    svcPacketEntities = 26,
    [global::ProtoBuf.ProtoEnum(Name = @"svc_TempEntities")]
    svcTempEntities = 27,
    [global::ProtoBuf.ProtoEnum(Name = @"svc_Prefetch")]
    svcPrefetch = 28,
    [global::ProtoBuf.ProtoEnum(Name = @"svc_Menu")]
    svcMenu = 29,
    [global::ProtoBuf.ProtoEnum(Name = @"svc_GameEventList")]
    svcGameEventList = 30,
    [global::ProtoBuf.ProtoEnum(Name = @"svc_GetCvarValue")]
    svcGetCvarValue = 31,
}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
